// Zork I: The Great Underground Empire
// (c) 1980 by INFOCOM, Inc.
// C port and parser (c) 2021 by Donnie Russell II

// This source code is provided for personal, educational use only.
// You are welcome to use this source code to develop your own works,
// but the story-related content belongs to the original authors of Zork.



#include "_def.h"



//scenery: single words separated by commas with no whitespace

struct ROOM_STRUCT Room[NUM_ROOMS] =
{
  //                          scenery cur/init prop

  /* null room                */  { 0, 0, 0                                              },

  /* ROOM_WEST_OF_HOUSE       */  { 0, 0, R_SACRED | R_LIT                               },
  /* ROOM_STONE_BARROW        */  { 0, 0, R_SACRED | R_LIT                               },
  /* ROOM_NORTH_OF_HOUSE      */  { 0, 0, R_SACRED | R_LIT                               },
  /* ROOM_SOUTH_OF_HOUSE      */  { 0, 0, R_SACRED | R_LIT                               },
  /* ROOM_EAST_OF_HOUSE       */  { 0, 0, R_SACRED | R_LIT                               },
  /* ROOM_FOREST_1            */  { 0, 0, R_SACRED | R_LIT                               },
  /* ROOM_FOREST_2            */  { 0, 0, R_SACRED | R_LIT                               },
  /* ROOM_MOUNTAINS           */  { 0, 0, R_SACRED | R_LIT                               },
  /* ROOM_FOREST_3            */  { 0, 0, R_SACRED | R_LIT                               },
  /* ROOM_PATH                */  { 0, 0, R_SACRED | R_LIT                               },
  /* ROOM_UP_A_TREE           */  { 0, 0, R_SACRED | R_LIT                               },
  /* ROOM_GRATING_CLEARING    */  { 0, 0, R_SACRED | R_LIT                               },
  /* ROOM_CLEARING            */  { 0, 0, R_SACRED | R_LIT                               },
  /* ROOM_KITCHEN             */  { 0, 0, R_SACRED | R_LIT                               },
  /* ROOM_ATTIC               */  { 0, 0, R_SACRED                                       },
  /* ROOM_LIVING_ROOM         */  { 0, 0, R_SACRED | R_LIT                               },
  /* ROOM_CELLAR              */  { 0, 0, 0                                              },
  /* ROOM_TROLL_ROOM          */  { 0, 0, 0                                              },
  /* ROOM_EAST_OF_CHASM       */  { 0, 0, 0                                              },
  /* ROOM_GALLERY             */  { 0, 0, R_LIT                                          },
  /* ROOM_STUDIO              */  { 0, 0, 0                                              },
  /* ROOM_MAZE_1              */  { 0, 0, R_ALWAYSDESC | R_MAZE                          },
  /* ROOM_MAZE_2              */  { 0, 0, R_ALWAYSDESC | R_MAZE                          },
  /* ROOM_MAZE_3              */  { 0, 0, R_ALWAYSDESC | R_MAZE                          },
  /* ROOM_MAZE_4              */  { 0, 0, R_ALWAYSDESC | R_MAZE                          },
  /* ROOM_DEAD_END_1          */  { 0, 0, R_ALWAYSDESC | R_MAZE                          },
  /* ROOM_MAZE_5              */  { 0, 0, R_ALWAYSDESC | R_MAZE                          },
  /* ROOM_DEAD_END_2          */  { 0, 0, R_ALWAYSDESC | R_MAZE                          },
  /* ROOM_MAZE_6              */  { 0, 0, R_ALWAYSDESC | R_MAZE                          },
  /* ROOM_MAZE_7              */  { 0, 0, R_ALWAYSDESC | R_MAZE                          },
  /* ROOM_MAZE_8              */  { 0, 0, R_ALWAYSDESC | R_MAZE                          },
  /* ROOM_DEAD_END_3          */  { 0, 0, R_ALWAYSDESC | R_MAZE                          },
  /* ROOM_MAZE_9              */  { 0, 0, R_ALWAYSDESC | R_MAZE                          },
  /* ROOM_MAZE_10             */  { 0, 0, R_ALWAYSDESC | R_MAZE                          },
  /* ROOM_MAZE_11             */  { 0, 0, R_ALWAYSDESC | R_MAZE                          },
  /* ROOM_GRATING_ROOM        */  { 0, 0, 0                                              },
  /* ROOM_MAZE_12             */  { 0, 0, R_ALWAYSDESC | R_MAZE                          },
  /* ROOM_DEAD_END_4          */  { 0, 0, R_ALWAYSDESC | R_MAZE                          },
  /* ROOM_MAZE_13             */  { 0, 0, R_ALWAYSDESC | R_MAZE                          },
  /* ROOM_MAZE_14             */  { 0, 0, R_ALWAYSDESC | R_MAZE                          },
  /* ROOM_MAZE_15             */  { 0, 0, R_ALWAYSDESC | R_MAZE                          },
  /* ROOM_CYCLOPS_ROOM        */  { 0, 0, 0                                              },
  /* ROOM_STRANGE_PASSAGE     */  { 0, 0, 0                                              },
  /* ROOM_TREASURE_ROOM       */  { 0, 0, 0                                              },
  /* ROOM_RESERVOIR_SOUTH     */  { 0, 0, R_WATERHERE                                    },
  /* ROOM_RESERVOIR           */  { 0, 0, R_WATERHERE | R_BODYOFWATER                    },
  /* ROOM_RESERVOIR_NORTH     */  { 0, 0, R_WATERHERE                                    },
  /* ROOM_STREAM_VIEW         */  { 0, 0, R_WATERHERE                                    },
  /* ROOM_IN_STREAM           */  { 0, 0, R_WATERHERE | R_BODYOFWATER                    },
  /* ROOM_MIRROR_ROOM_1       */  { 0, 0, 0                                              },
  /* ROOM_MIRROR_ROOM_2       */  { 0, 0, R_LIT                                          },
  /* ROOM_SMALL_CAVE          */  { 0, 0, 0                                              },
  /* ROOM_TINY_CAVE           */  { 0, 0, 0                                              },
  /* ROOM_COLD_PASSAGE        */  { 0, 0, 0                                              },
  /* ROOM_NARROW_PASSAGE      */  { 0, 0, 0                                              },
  /* ROOM_WINDING_PASSAGE     */  { 0, 0, 0                                              },
  /* ROOM_TWISTING_PASSAGE    */  { 0, 0, 0                                              },
  /* ROOM_ATLANTIS_ROOM       */  { 0, 0, 0                                              },
  /* ROOM_EW_PASSAGE          */  { 0, 0, 0                                              },
  /* ROOM_ROUND_ROOM          */  { 0, 0, 0                                              },
  /* ROOM_DEEP_CANYON         */  { 0, 0, 0                                              },
  /* ROOM_DAMP_CAVE           */  { 0, 0, 0                                              },
  /* ROOM_LOUD_ROOM           */  { 0, 0, 0                                              },
  /* ROOM_NS_PASSAGE          */  { 0, 0, 0                                              },
  /* ROOM_CHASM_ROOM          */  { 0, 0, 0                                              },
  /* ROOM_ENTRANCE_TO_HADES   */  { 0, 0, R_LIT                                          },
  /* ROOM_LAND_OF_LIVING_DEAD */  { 0, 0, R_LIT                                          },
  /* ROOM_ENGRAVINGS_CAVE     */  { 0, 0, 0                                              },
  /* ROOM_EGYPT_ROOM          */  { 0, 0, 0                                              },
  /* ROOM_DOME_ROOM           */  { 0, 0, 0                                              },
  /* ROOM_TORCH_ROOM          */  { 0, 0, 0                                              },
  /* ROOM_NORTH_TEMPLE        */  { 0, 0, R_SACRED | R_LIT                               },
  /* ROOM_SOUTH_TEMPLE        */  { 0, 0, R_SACRED | R_LIT                               },
  /* ROOM_DAM_ROOM            */  { 0, 0, R_WATERHERE | R_LIT                            },
  /* ROOM_DAM_LOBBY           */  { 0, 0, R_LIT                                          },
  /* ROOM_MAINTENANCE_ROOM    */  { 0, 0, 0                                              },
  /* ROOM_DAM_BASE            */  { 0, 0, R_SACRED | R_WATERHERE | R_LIT                 },
  /* ROOM_RIVER_1             */  { 0, 0, R_SACRED | R_WATERHERE | R_LIT | R_BODYOFWATER },
  /* ROOM_RIVER_2             */  { 0, 0, R_SACRED | R_WATERHERE | R_BODYOFWATER         },
  /* ROOM_RIVER_3             */  { 0, 0, R_SACRED | R_WATERHERE | R_BODYOFWATER         },
  /* ROOM_WHITE_CLIFFS_NORTH  */  { 0, 0, R_SACRED | R_WATERHERE                         },
  /* ROOM_WHITE_CLIFFS_SOUTH  */  { 0, 0, R_SACRED | R_WATERHERE                         },
  /* ROOM_RIVER_4             */  { 0, 0, R_SACRED | R_WATERHERE | R_BODYOFWATER         },
  /* ROOM_RIVER_5             */  { 0, 0, R_SACRED | R_WATERHERE | R_LIT | R_BODYOFWATER },
  /* ROOM_SHORE               */  { 0, 0, R_SACRED | R_WATERHERE | R_LIT                 },
  /* ROOM_SANDY_BEACH         */  { 0, 0, R_SACRED | R_WATERHERE                         },
  /* ROOM_SANDY_CAVE          */  { 0, 0, 0                                              },
  /* ROOM_ARAGAIN_FALLS       */  { 0, 0, R_SACRED | R_WATERHERE | R_LIT                 },
  /* ROOM_ON_RAINBOW          */  { 0, 0, R_SACRED | R_LIT                               },
  /* ROOM_END_OF_RAINBOW      */  { 0, 0, R_WATERHERE | R_LIT                            },
  /* ROOM_CANYON_BOTTOM       */  { 0, 0, R_SACRED | R_WATERHERE | R_LIT                 },
  /* ROOM_CLIFF_MIDDLE        */  { 0, 0, R_SACRED | R_LIT                               },
  /* ROOM_CANYON_VIEW         */  { 0, 0, R_SACRED | R_LIT                               },
  /* ROOM_MINE_ENTRANCE       */  { 0, 0, 0                                              },
  /* ROOM_SQUEEKY_ROOM        */  { 0, 0, 0                                              },
  /* ROOM_BAT_ROOM            */  { 0, 0, R_SACRED                                       },
  /* ROOM_SHAFT_ROOM          */  { 0, 0, 0                                              },
  /* ROOM_SMELLY_ROOM         */  { 0, 0, 0                                              },
  /* ROOM_GAS_ROOM            */  { 0, 0, R_SACRED                                       },
  /* ROOM_LADDER_TOP          */  { 0, 0, 0                                              },
  /* ROOM_LADDER_BOTTOM       */  { 0, 0, 0                                              },
  /* ROOM_DEAD_END_5          */  { 0, 0, 0                                              },
  /* ROOM_TIMBER_ROOM         */  { 0, 0, R_SACRED                                       },
  /* ROOM_LOWER_SHAFT         */  { 0, 0, R_SACRED                                       },
  /* ROOM_MACHINE_ROOM        */  { 0, 0, 0                                              },
  /* ROOM_MINE_1              */  { 0, 0, 0                                              },
  /* ROOM_MINE_2              */  { 0, 0, 0                                              },
  /* ROOM_MINE_3              */  { 0, 0, 0                                              },
  /* ROOM_MINE_4              */  { 0, 0, 0                                              },
  /* ROOM_SLIDE_ROOM          */  { 0, 0, 0                                              }
};



//collection of scenery nouns from all rooms
//single words separated by commas with no whitespace
//alphabetical order is not necessary

char *SceneryNouns = "test1,test2";



struct ROOM_PASSAGES_STRUCT RoomPassages[NUM_ROOMS] =
{
  /* null room                */  { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },

                                  // N  S  E  W  NE  NW  SE  SW  U  D

  /* ROOM_WEST_OF_HOUSE       */  { ROOM_NORTH_OF_HOUSE, ROOM_SOUTH_OF_HOUSE, BL1, ROOM_FOREST_1, ROOM_NORTH_OF_HOUSE, BL0, ROOM_SOUTH_OF_HOUSE, BL0, BL0, BL0 },
  /* ROOM_STONE_BARROW        */  { BL0, BL0, BL0, BL0, ROOM_WEST_OF_HOUSE, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_NORTH_OF_HOUSE      */  { ROOM_PATH, BL2, ROOM_EAST_OF_HOUSE, ROOM_WEST_OF_HOUSE, BL0, BL0, ROOM_EAST_OF_HOUSE, ROOM_WEST_OF_HOUSE, BL0, BL0 },
  /* ROOM_SOUTH_OF_HOUSE      */  { BL2, ROOM_FOREST_3, ROOM_EAST_OF_HOUSE, ROOM_WEST_OF_HOUSE, ROOM_EAST_OF_HOUSE, ROOM_WEST_OF_HOUSE, BL0, BL0, BL0, BL0 },
  /* ROOM_EAST_OF_HOUSE       */  { ROOM_NORTH_OF_HOUSE, ROOM_SOUTH_OF_HOUSE, ROOM_CLEARING, BL0, BL0, ROOM_NORTH_OF_HOUSE, BL0, ROOM_SOUTH_OF_HOUSE, BL0, BL0 },
  /* ROOM_FOREST_1            */  { ROOM_GRATING_CLEARING, ROOM_FOREST_3, ROOM_PATH, BL3, BL0, BL0, BL0, BL0, BL4, BL0 },
  /* ROOM_FOREST_2            */  { BL5, ROOM_CLEARING, ROOM_MOUNTAINS, ROOM_PATH, BL0, BL0, BL0, BL0, BL4, BL0 },
  /* ROOM_MOUNTAINS           */  { ROOM_FOREST_2, ROOM_FOREST_2, BL6, ROOM_FOREST_2, BL0, BL0, BL0, BL0, BL6, BL0 },
  /* ROOM_FOREST_3            */  { ROOM_CLEARING, BL7, BL8, ROOM_FOREST_1, BL0, ROOM_SOUTH_OF_HOUSE, BL0, BL0, BL4, BL0 },
  /* ROOM_PATH                */  { ROOM_GRATING_CLEARING, ROOM_NORTH_OF_HOUSE, ROOM_FOREST_2, ROOM_FOREST_1, BL0, BL0, BL0, BL0, ROOM_UP_A_TREE, BL0 },
  /* ROOM_UP_A_TREE           */  { BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL9, ROOM_PATH },
  /* ROOM_GRATING_CLEARING    */  { BL5, ROOM_PATH, ROOM_FOREST_2, ROOM_FOREST_1, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_CLEARING            */  { ROOM_FOREST_2, ROOM_FOREST_3, ROOM_CANYON_VIEW, ROOM_EAST_OF_HOUSE, BL0, BL0, BL0, BL0, BL4, BL0 },
  /* ROOM_KITCHEN             */  { BL0, BL0, BL0, ROOM_LIVING_ROOM, BL0, BL0, BL0, BL0, ROOM_ATTIC, BL0 },
  /* ROOM_ATTIC               */  { BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0, ROOM_KITCHEN },
  /* ROOM_LIVING_ROOM         */  { BL0, BL0, ROOM_KITCHEN, BL0, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_CELLAR              */  { ROOM_TROLL_ROOM, ROOM_EAST_OF_CHASM, BL0, BLA, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_TROLL_ROOM          */  { BL0, ROOM_CELLAR, BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_EAST_OF_CHASM       */  { ROOM_CELLAR, BL0, ROOM_GALLERY, BL0, BL0, BL0, BL0, BL0, BL0, BLB },
  /* ROOM_GALLERY             */  { ROOM_STUDIO, BL0, BL0, ROOM_EAST_OF_CHASM, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_STUDIO              */  { BL0, ROOM_GALLERY, BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_MAZE_1              */  { ROOM_MAZE_1, ROOM_MAZE_2, ROOM_TROLL_ROOM, ROOM_MAZE_4, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_MAZE_2              */  { BL0, ROOM_MAZE_1, ROOM_MAZE_3, BL0, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_MAZE_3              */  { ROOM_MAZE_4, BL0, BL0, ROOM_MAZE_2, BL0, BL0, BL0, BL0, ROOM_MAZE_5, BL0 },
  /* ROOM_MAZE_4              */  { ROOM_MAZE_1, BL0, ROOM_DEAD_END_1, ROOM_MAZE_3, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_DEAD_END_1          */  { BL0, ROOM_MAZE_4, BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_MAZE_5              */  { ROOM_MAZE_3, BL0, ROOM_DEAD_END_2, BL0, BL0, BL0, BL0, ROOM_MAZE_6, BL0, BL0 },
  /* ROOM_DEAD_END_2          */  { BL0, BL0, BL0, ROOM_MAZE_5, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_MAZE_6              */  { BL0, BL0, ROOM_MAZE_7, ROOM_MAZE_6, BL0, BL0, BL0, BL0, ROOM_MAZE_9, ROOM_MAZE_5 },
  /* ROOM_MAZE_7              */  { BL0, ROOM_MAZE_15, ROOM_MAZE_8, ROOM_MAZE_6, BL0, BL0, BL0, BL0, ROOM_MAZE_14, BL0 },
  /* ROOM_MAZE_8              */  { BL0, BL0, BL0, ROOM_MAZE_8, ROOM_MAZE_7, BL0, ROOM_DEAD_END_3, BL0, BL0, BL0 },
  /* ROOM_DEAD_END_3          */  { ROOM_MAZE_8, BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_MAZE_9              */  { ROOM_MAZE_6, ROOM_MAZE_13, ROOM_MAZE_10, ROOM_MAZE_12, BL0, ROOM_MAZE_9, BL0, BL0, BL0, BL0 },
  /* ROOM_MAZE_10             */  { BL0, BL0, ROOM_MAZE_9, ROOM_MAZE_13, BL0, BL0, BL0, BL0, ROOM_MAZE_11, BL0 },
  /* ROOM_MAZE_11             */  { BL0, BL0, BL0, BL0, ROOM_GRATING_ROOM, ROOM_MAZE_13, BL0, ROOM_MAZE_12, BL0, ROOM_MAZE_10 },
  /* ROOM_GRATING_ROOM        */  { BL0, BL0, BL0, BL0, BL0, BL0, BL0, ROOM_MAZE_11, BL0, BL0 },
  /* ROOM_MAZE_12             */  { ROOM_DEAD_END_4, BL0, ROOM_MAZE_13, BL0, BL0, BL0, BL0, ROOM_MAZE_11, ROOM_MAZE_9, BL0 },
  /* ROOM_DEAD_END_4          */  { BL0, ROOM_MAZE_12, BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_MAZE_13             */  { BL0, ROOM_MAZE_10, ROOM_MAZE_9, ROOM_MAZE_11, BL0, BL0, BL0, BL0, BL0, ROOM_MAZE_12 },
  /* ROOM_MAZE_14             */  { BL0, ROOM_MAZE_7, BL0, ROOM_MAZE_15, ROOM_MAZE_7, ROOM_MAZE_14, BL0, BL0, BL0, BL0 },
  /* ROOM_MAZE_15             */  { BL0, ROOM_MAZE_7, BL0, ROOM_MAZE_14, BL0, BL0, ROOM_CYCLOPS_ROOM, BL0, BL0, BL0 },
  /* ROOM_CYCLOPS_ROOM        */  { BL0, BL0, BL0, BL0, BL0, ROOM_MAZE_15, BL0, BL0, BL0, BL0 },
  /* ROOM_STRANGE_PASSAGE     */  { BL0, BL0, ROOM_LIVING_ROOM, ROOM_CYCLOPS_ROOM, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_TREASURE_ROOM       */  { BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0, ROOM_CYCLOPS_ROOM },
  /* ROOM_RESERVOIR_SOUTH     */  { BL0, BL0, ROOM_DAM_ROOM, ROOM_STREAM_VIEW, BL0, BL0, ROOM_DEEP_CANYON, ROOM_CHASM_ROOM, BL0, BL0 },
  /* ROOM_RESERVOIR           */  { ROOM_RESERVOIR_NORTH, ROOM_RESERVOIR_SOUTH, BL0, ROOM_IN_STREAM, BL0, BL0, BL0, BL0, ROOM_IN_STREAM, BLC },
  /* ROOM_RESERVOIR_NORTH     */  { ROOM_ATLANTIS_ROOM, BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_STREAM_VIEW         */  { BL0, BL0, ROOM_RESERVOIR_SOUTH, BLD, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_IN_STREAM           */  { BL0, ROOM_STREAM_VIEW, ROOM_RESERVOIR, BLE, BL0, BL0, BL0, BL0, BLE, ROOM_RESERVOIR },
  /* ROOM_MIRROR_ROOM_1       */  { ROOM_COLD_PASSAGE, BL0, ROOM_SMALL_CAVE, ROOM_TWISTING_PASSAGE, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_MIRROR_ROOM_2       */  { ROOM_NARROW_PASSAGE, BL0, ROOM_TINY_CAVE, ROOM_WINDING_PASSAGE, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_SMALL_CAVE          */  { ROOM_MIRROR_ROOM_1, ROOM_ATLANTIS_ROOM, BL0, ROOM_TWISTING_PASSAGE, BL0, BL0, BL0, BL0, BL0, ROOM_ATLANTIS_ROOM },
  /* ROOM_TINY_CAVE           */  { ROOM_MIRROR_ROOM_2, BL0, BL0, ROOM_WINDING_PASSAGE, BL0, BL0, BL0, BL0, BL0, ROOM_ENTRANCE_TO_HADES },
  /* ROOM_COLD_PASSAGE        */  { BL0, ROOM_MIRROR_ROOM_1, BL0, ROOM_SLIDE_ROOM, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_NARROW_PASSAGE      */  { ROOM_ROUND_ROOM, ROOM_MIRROR_ROOM_2, BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_WINDING_PASSAGE     */  { ROOM_MIRROR_ROOM_2, BL0, ROOM_TINY_CAVE, BL0, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_TWISTING_PASSAGE    */  { ROOM_MIRROR_ROOM_1, BL0, ROOM_SMALL_CAVE, BL0, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_ATLANTIS_ROOM       */  { BL0, ROOM_RESERVOIR_NORTH, BL0, BL0, BL0, BL0, BL0, BL0, ROOM_SMALL_CAVE, BL0 },
  /* ROOM_EW_PASSAGE          */  { ROOM_CHASM_ROOM, BL0, ROOM_ROUND_ROOM, ROOM_TROLL_ROOM, BL0, BL0, BL0, BL0, BL0, ROOM_CHASM_ROOM },
  /* ROOM_ROUND_ROOM          */  { ROOM_NS_PASSAGE, ROOM_NARROW_PASSAGE, ROOM_LOUD_ROOM, ROOM_EW_PASSAGE, BL0, BL0, ROOM_ENGRAVINGS_CAVE, BL0, BL0, BL0 },
  /* ROOM_DEEP_CANYON         */  { BL0, BL0, ROOM_DAM_ROOM, BL0, BL0, ROOM_RESERVOIR_SOUTH, BL0, ROOM_NS_PASSAGE, BL0, ROOM_LOUD_ROOM },
  /* ROOM_DAMP_CAVE           */  { BL0, BLF, ROOM_WHITE_CLIFFS_NORTH, ROOM_LOUD_ROOM, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_LOUD_ROOM           */  { BL0, BL0, ROOM_DAMP_CAVE, ROOM_ROUND_ROOM, BL0, BL0, BL0, BL0, ROOM_DEEP_CANYON, BL0 },
  /* ROOM_NS_PASSAGE          */  { ROOM_CHASM_ROOM, ROOM_ROUND_ROOM, BL0, BL0, ROOM_DEEP_CANYON, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_CHASM_ROOM          */  { BL0, ROOM_NS_PASSAGE, BL0, BL0, ROOM_RESERVOIR_SOUTH, BL0, BL0, ROOM_EW_PASSAGE, ROOM_EW_PASSAGE, BLG },
  /* ROOM_ENTRANCE_TO_HADES   */  { BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0, ROOM_TINY_CAVE, BL0 },
  /* ROOM_LAND_OF_LIVING_DEAD */  { ROOM_ENTRANCE_TO_HADES, BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_ENGRAVINGS_CAVE     */  { BL0, BL0, ROOM_DOME_ROOM, BL0, BL0, ROOM_ROUND_ROOM, BL0, BL0, BL0, BL0 },
  /* ROOM_EGYPT_ROOM          */  { BL0, BL0, BL0, ROOM_NORTH_TEMPLE, BL0, BL0, BL0, BL0, ROOM_NORTH_TEMPLE, BL0 },
  /* ROOM_DOME_ROOM           */  { BL0, BL0, BL0, ROOM_ENGRAVINGS_CAVE, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_TORCH_ROOM          */  { BL0, ROOM_NORTH_TEMPLE, BL0, BL0, BL0, BL0, BL0, BL0, BLH, ROOM_NORTH_TEMPLE },
  /* ROOM_NORTH_TEMPLE        */  { ROOM_TORCH_ROOM, ROOM_SOUTH_TEMPLE, ROOM_EGYPT_ROOM, BL0, BL0, BL0, BL0, BL0, ROOM_TORCH_ROOM, ROOM_EGYPT_ROOM },
  /* ROOM_SOUTH_TEMPLE        */  { ROOM_NORTH_TEMPLE, BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_DAM_ROOM            */  { ROOM_DAM_LOBBY, ROOM_DEEP_CANYON, ROOM_DAM_BASE, ROOM_RESERVOIR_SOUTH, BL0, BL0, BL0, BL0, BL0, ROOM_DAM_BASE },
  /* ROOM_DAM_LOBBY           */  { BL0, ROOM_DAM_ROOM, BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_MAINTENANCE_ROOM    */  { BL0, ROOM_DAM_LOBBY, BL0, ROOM_DAM_LOBBY, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_DAM_BASE            */  { ROOM_DAM_ROOM, BL0, BL0, BL0, BL0, BL0, BL0, BL0, ROOM_DAM_ROOM, BL0 },
  /* ROOM_RIVER_1             */  { BL0, BL0, BLI, ROOM_DAM_BASE, BL0, BL0, BL0, BL0, BLJ, ROOM_RIVER_2 },
  /* ROOM_RIVER_2             */  { BL0, BL0, BLI, BLK, BL0, BL0, BL0, BL0, BLJ, ROOM_RIVER_3 },
  /* ROOM_RIVER_3             */  { BL0, BL0, BL0, ROOM_WHITE_CLIFFS_NORTH, BL0, BL0, BL0, BL0, BLJ, ROOM_RIVER_4 },
  /* ROOM_WHITE_CLIFFS_NORTH  */  { BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_WHITE_CLIFFS_SOUTH  */  { BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_RIVER_4             */  { BL0, BL0, ROOM_SANDY_BEACH, ROOM_WHITE_CLIFFS_SOUTH, BL0, BL0, BL0, BL0, BLJ, ROOM_RIVER_5 },
  /* ROOM_RIVER_5             */  { BL0, BL0, ROOM_SHORE, BL0, BL0, BL0, BL0, BL0, BLJ, BL0 },
  /* ROOM_SHORE               */  { ROOM_SANDY_BEACH, ROOM_ARAGAIN_FALLS, BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_SANDY_BEACH         */  { BL0, ROOM_SHORE, BL0, BL0, ROOM_SANDY_CAVE, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_SANDY_CAVE          */  { BL0, BL0, BL0, BL0, BL0, BL0, BL0, ROOM_SANDY_BEACH, BL0, BL0 },
  /* ROOM_ARAGAIN_FALLS       */  { ROOM_SHORE, BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0, BLL },
  /* ROOM_ON_RAINBOW          */  { BL0, BL0, ROOM_ARAGAIN_FALLS, ROOM_END_OF_RAINBOW, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_END_OF_RAINBOW      */  { BL0, BL0, BL0, BL0, BL0, BL0, BL0, ROOM_CANYON_BOTTOM, BL0, BL0 },
  /* ROOM_CANYON_BOTTOM       */  { ROOM_END_OF_RAINBOW, BL0, BL0, BL0, BL0, BL0, BL0, BL0, ROOM_CLIFF_MIDDLE, BL0 },
  /* ROOM_CLIFF_MIDDLE        */  { BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0, ROOM_CANYON_VIEW, ROOM_CANYON_BOTTOM },
  /* ROOM_CANYON_VIEW         */  { BL0, BL7, ROOM_CLIFF_MIDDLE, ROOM_FOREST_3, BL0, ROOM_CLEARING, BL0, BL0, BL0, ROOM_CLIFF_MIDDLE },
  /* ROOM_MINE_ENTRANCE       */  { BL0, ROOM_SLIDE_ROOM, BL0, ROOM_SQUEEKY_ROOM, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_SQUEEKY_ROOM        */  { ROOM_BAT_ROOM, BL0, ROOM_MINE_ENTRANCE, BL0, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_BAT_ROOM            */  { BL0, ROOM_SQUEEKY_ROOM, ROOM_SHAFT_ROOM, BL0, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_SHAFT_ROOM          */  { ROOM_SMELLY_ROOM, BL0, BL0, ROOM_BAT_ROOM, BL0, BL0, BL0, BL0, BL0, BLM },
  /* ROOM_SMELLY_ROOM         */  { BL0, ROOM_SHAFT_ROOM, BL0, BL0, BL0, BL0, BL0, BL0, BL0, ROOM_GAS_ROOM },
  /* ROOM_GAS_ROOM            */  { BL0, BL0, ROOM_MINE_1, BL0, BL0, BL0, BL0, BL0, ROOM_SMELLY_ROOM, BL0 },
  /* ROOM_LADDER_TOP          */  { BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0, ROOM_MINE_4, ROOM_LADDER_BOTTOM },
  /* ROOM_LADDER_BOTTOM       */  { BL0, ROOM_DEAD_END_5, BL0, ROOM_TIMBER_ROOM, BL0, BL0, BL0, BL0, ROOM_LADDER_TOP, BL0 },
  /* ROOM_DEAD_END_5          */  { ROOM_LADDER_BOTTOM, BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_TIMBER_ROOM         */  { BL0, BL0, ROOM_LADDER_BOTTOM, BL0, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_LOWER_SHAFT         */  { BL0, ROOM_MACHINE_ROOM, BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_MACHINE_ROOM        */  { ROOM_LOWER_SHAFT, BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_MINE_1              */  { ROOM_GAS_ROOM, BL0, ROOM_MINE_1, BL0, ROOM_MINE_2, BL0, BL0, BL0, BL0, BL0 },
  /* ROOM_MINE_2              */  { ROOM_MINE_2, ROOM_MINE_1, BL0, BL0, BL0, BL0, ROOM_MINE_3, BL0, BL0, BL0 },
  /* ROOM_MINE_3              */  { BL0, ROOM_MINE_3, ROOM_MINE_2, BL0, BL0, BL0, BL0, ROOM_MINE_4, BL0, BL0 },
  /* ROOM_MINE_4              */  { ROOM_MINE_3, BL0, BL0, ROOM_MINE_4, BL0, BL0, BL0, BL0, BL0, ROOM_LADDER_TOP },
  /* ROOM_SLIDE_ROOM          */  { ROOM_MINE_ENTRANCE, BL0, ROOM_COLD_PASSAGE, BL0, BL0, BL0, BL0, BL0, BL0, ROOM_CELLAR }
};



#define INSIDE  2048

struct OBJ_STRUCT Obj[NUM_OBJECTS] =
{
//     label                      init_loc                     loc  size capacity order prop    init / cur
//                                                                                              thiefvalue
  { /* OBJ_NOTHING            */  0                            , 0 ,   0 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_YOU                */  ROOM_WEST_OF_HOUSE           , 0 ,   0 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_CYCLOPS            */  ROOM_CYCLOPS_ROOM            , 0 ,   0 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_GHOSTS             */  ROOM_ENTRANCE_TO_HADES       , 0 ,   0 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_BAT                */  ROOM_BAT_ROOM                , 0 ,   0 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_THIEF              */  ROOM_ROUND_ROOM              , 0 ,   0 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_TROLL              */  ROOM_TROLL_ROOM              , 0 ,   0 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_LOWERED_BASKET     */  ROOM_LOWER_SHAFT             , 0 ,   0 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_RAISED_BASKET      */  ROOM_SHAFT_ROOM              , 0 ,   0 ,     50 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_TROPHY_CASE        */  ROOM_LIVING_ROOM             , 0 ,   0 ,  10000 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_MACHINE            */  ROOM_MACHINE_ROOM            , 0 ,   0 ,     50 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_MAILBOX            */  ROOM_WEST_OF_HOUSE           , 0 ,   0 ,     10 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_WATER              */    INSIDE + OBJ_BOTTLE        , 0 ,   4 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_SKULL              */  ROOM_LAND_OF_LIVING_DEAD     , 0 ,   0 ,      0 ,   0 ,  0 , 10 , 0 },
  { /* OBJ_TIMBERS            */  ROOM_TIMBER_ROOM             , 0 ,  50 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_LUNCH              */    INSIDE + OBJ_SANDWICH_BAG  , 0 ,   0 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_BELL               */  ROOM_NORTH_TEMPLE            , 0 ,   0 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_HOT_BELL           */  0                            , 0 ,   0 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_BOOK               */  ROOM_SOUTH_TEMPLE            , 0 ,  10 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_AXE                */    INSIDE + OBJ_TROLL         , 0 ,  25 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_BROKEN_LAMP        */  0                            , 0 ,   0 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_SCEPTRE            */    INSIDE + OBJ_COFFIN        , 0 ,   3 ,      0 ,   0 ,  0 ,  6 , 0 },
  { /* OBJ_SANDWICH_BAG       */  ROOM_KITCHEN                 , 0 ,   9 ,      9 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_CHALICE            */  ROOM_TREASURE_ROOM           , 0 ,  10 ,      5 ,   0 ,  0 ,  5 , 0 },
  { /* OBJ_GARLIC             */    INSIDE + OBJ_SANDWICH_BAG  , 0 ,   4 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_TRIDENT            */  ROOM_ATLANTIS_ROOM           , 0 ,  20 ,      0 ,   0 ,  0 , 11 , 0 },
  { /* OBJ_BOTTLE             */  ROOM_KITCHEN                 , 0 ,   0 ,      4 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_COFFIN             */  ROOM_EGYPT_ROOM              , 0 ,  55 ,     35 ,   0 ,  0 , 15 , 0 },
  { /* OBJ_PUMP               */  ROOM_RESERVOIR_NORTH         , 0 ,   0 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_DIAMOND            */  0                            , 0 ,   0 ,      0 ,   0 ,  0 , 10 , 0 },
  { /* OBJ_JADE               */  ROOM_BAT_ROOM                , 0 ,  10 ,      0 ,   0 ,  0 ,  5 , 0 },
  { /* OBJ_KNIFE              */  ROOM_ATTIC                   , 0 ,   0 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_BURNED_OUT_LANTERN */  ROOM_MAZE_5                  , 0 ,  20 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_BAG_OF_COINS       */  ROOM_MAZE_5                  , 0 ,  15 ,      0 ,   0 ,  0 ,  5 , 0 },
  { /* OBJ_LAMP               */  ROOM_LIVING_ROOM             , 0 ,  15 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_EMERALD            */    INSIDE + OBJ_BUOY          , 0 ,   0 ,      0 ,   0 ,  0 , 10 , 0 },
  { /* OBJ_ADVERTISEMENT      */    INSIDE + OBJ_MAILBOX       , 0 ,   2 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_INFLATED_BOAT      */  0                            , 0 ,  20 ,    100 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_MATCH              */  ROOM_DAM_LOBBY               , 0 ,   2 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_PAINTING           */  ROOM_GALLERY                 , 0 ,  15 ,      0 ,   0 ,  0 ,  6 , 0 },
  { /* OBJ_CANDLES            */  ROOM_SOUTH_TEMPLE            , 0 ,  10 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_GUNK               */  0                            , 0 ,  10 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_LEAVES             */  ROOM_GRATING_CLEARING        , 0 ,  25 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_PUNCTURED_BOAT     */  0                            , 0 ,  20 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_INFLATABLE_BOAT    */  ROOM_DAM_BASE                , 0 ,  20 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_BAR                */  ROOM_LOUD_ROOM               , 0 ,  20 ,      0 ,   0 ,  0 ,  5 , 0 },
  { /* OBJ_POT_OF_GOLD        */  ROOM_END_OF_RAINBOW          , 0 ,  15 ,      0 ,   0 ,  0 , 10 , 0 },
  { /* OBJ_BUOY               */  ROOM_RIVER_4                 , 0 ,  10 ,     20 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_ROPE               */  ROOM_ATTIC                   , 0 ,  10 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_RUSTY_KNIFE        */  ROOM_MAZE_5                  , 0 ,  20 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_BRACELET           */  ROOM_GAS_ROOM                , 0 ,  10 ,      0 ,   0 ,  0 ,  5 , 0 },
  { /* OBJ_TOOL_CHEST         */  ROOM_MAINTENANCE_ROOM        , 0 ,   0 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_SCREWDRIVER        */  ROOM_MAINTENANCE_ROOM        , 0 ,   0 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_KEYS               */  ROOM_MAZE_5                  , 0 ,  10 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_SHOVEL             */  ROOM_SANDY_BEACH             , 0 ,  15 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_COAL               */  ROOM_DEAD_END_5              , 0 ,  20 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_SCARAB             */  ROOM_SANDY_CAVE              , 0 ,   8 ,      0 ,   0 ,  0 ,  5 , 0 },
  { /* OBJ_LARGE_BAG          */    INSIDE + OBJ_THIEF         , 0 ,   0 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_STILETTO           */    INSIDE + OBJ_THIEF         , 0 ,  10 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_SWORD              */  ROOM_LIVING_ROOM             , 0 ,  30 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_MAP                */    INSIDE + OBJ_TROPHY_CASE   , 0 ,   2 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_BOAT_LABEL         */    INSIDE + OBJ_INFLATED_BOAT , 0 ,   2 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_TORCH              */  ROOM_TORCH_ROOM              , 0 ,  20 ,      0 ,   0 ,  0 ,  6 , 0 },
  { /* OBJ_GUIDE              */  ROOM_DAM_LOBBY               , 0 ,   0 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_TRUNK              */  ROOM_RESERVOIR               , 0 ,  35 ,      0 ,   0 ,  0 ,  5 , 0 },
  { /* OBJ_TUBE               */  ROOM_MAINTENANCE_ROOM        , 0 ,   5 ,      7 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_PUTTY              */    INSIDE + OBJ_TUBE          , 0 ,   6 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_OWNERS_MANUAL      */  ROOM_STUDIO                  , 0 ,   0 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_WRENCH             */  ROOM_MAINTENANCE_ROOM        , 0 ,  10 ,      0 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_NEST               */  ROOM_UP_A_TREE               , 0 ,   0 ,     20 ,   0 ,  0 ,  0 , 0 },
  { /* OBJ_EGG                */    INSIDE + OBJ_NEST          , 0 ,   0 ,      6 ,   0 ,  0 ,  5 , 0 },
  { /* OBJ_BROKEN_EGG         */  0                            , 0 ,   0 ,      6 ,   0 ,  0 ,  2 , 0 },
  { /* OBJ_BAUBLE             */  0                            , 0 ,   0 ,      0 ,   0 ,  0 ,  1 , 0 },
  { /* OBJ_CANARY             */    INSIDE + OBJ_EGG           , 0 ,   0 ,      0 ,   0 ,  0 ,  4 , 0 },
  { /* OBJ_BROKEN_CANARY      */    INSIDE + OBJ_BROKEN_EGG    , 0 ,   0 ,      0 ,   0 ,  0 ,  1 , 0 },
  { /* OBJ_ENGRAVINGS         */  ROOM_ENGRAVINGS_CAVE         , 0 ,   0 ,      0 ,   0 ,  0 ,  0 , 0 }
};



//phrase must contain a maximum of two words

//for matching to work, verb with adverb must come before same verb with no adverb

//words must be separated by exactly one space

//verbs don't need to (but should) be alphabetized

struct VERBTOACTION_STRUCT VerbToAction[] =
{
  //two words (verb-adverb)

  { "blow out"      , A_DEACTIVATE   },
  { "blow up"       , A_INFLATE      },
  { "break open"    , A_BREAK        },
  { "burn down"     , A_ACTIVATE     },
  { "climb down"    , A_CLIMBDOWN    },
  { "climb in"      , A_ENTER        },
  { "climb on"      , A_MOUNT        },
  { "climb out"     , A_EXIT         },
  { "climb through" , A_CLIMBTHROUGH },
  { "climb up"      , A_CLIMBUP      },
  { "dig in"        , A_DIG          },
  { "gaze at"       , A_EXAMINE      },
  { "gaze behind"   , A_LOOKBEHIND   },
  { "gaze in"       , A_LOOKIN       },
  { "gaze inside"   , A_LOOKIN       },
  { "gaze into"     , A_LOOKIN       },
  { "gaze on"       , A_LOOKON       },
  { "gaze through"  , A_LOOKTHROUGH  },
  { "gaze under"    , A_LOOKUNDER    },
  { "get in"        , A_ENTER        },
  { "get inside"    , A_ENTER        },
  { "get into"      , A_ENTER        },
  { "get off"       , A_DISMOUNT     },
  { "get on"        , A_MOUNT        },
  { "get out"       , A_EXIT         },
  { "go inside"     , A_ENTER        },
  { "go into"       , A_ENTER        },
  { "go through"    , A_CLIMBTHROUGH },
  { "jump across"   , A_JUMPOVER     },
  { "jump into"     , A_JUMPINTO     },
  { "jump over"     , A_JUMPOVER     },
  { "knock on"      , A_KNOCK        },
  { "knock with"    , A_KNOCK        },
  { "l at"          , A_EXAMINE      },
  { "l behind"      , A_LOOKBEHIND   },
  { "l in"          , A_LOOKIN       },
  { "l inside"      , A_LOOKIN       },
  { "l into"        , A_LOOKIN       },
  { "l on"          , A_LOOKON       },
  { "l through"     , A_LOOKTHROUGH  },
  { "l under"       , A_LOOKUNDER    },
  { "lay on"        , A_SLEEPON      },
  { "lift up"       , A_RAISE        },
  { "look at"       , A_EXAMINE      },
  { "look behind"   , A_LOOKBEHIND   },
  { "look in"       , A_LOOKIN       },
  { "look inside"   , A_LOOKIN       },
  { "look into"     , A_LOOKIN       },
  { "look on"       , A_LOOKON       },
  { "look through"  , A_LOOKTHROUGH  },
  { "look under"    , A_LOOKUNDER    },
  { "open up"       , A_OPEN         },
  { "pick up"       , A_TAKE         },
  { "pump up"       , A_INFLATE      },
  { "put down"      , A_DROP         },
  { "put on"        , A_WEAR         },
  { "put out"       , A_DEACTIVATE   },
  { "raise up"      , A_RAISE        },
  { "read from"     , A_READ         },
  { "sit in"        , A_ENTER        },
  { "sleep on"      , A_SLEEPON      },
  { "slide down"    , A_SLIDEDOWN    },
  { "slide up"      , A_SLIDEUP      },
  { "stand on"      , A_MOUNT        },
  { "stand up"      , A_DISEMBARK    },
  { "stare at"      , A_EXAMINE      },
  { "stare behind"  , A_LOOKBEHIND   },
  { "stare in"      , A_LOOKIN       },
  { "stare inside"  , A_LOOKIN       },
  { "stare into"    , A_LOOKIN       },
  { "stare on"      , A_LOOKON       },
  { "stare through" , A_LOOKTHROUGH  },
  { "stare under"   , A_LOOKUNDER    },
  { "swim in"       , A_SWIM         },
  { "swim across"   , A_SWIM         },
  { "take off"      , A_REMOVE       },
  { "take out"      , A_TAKE         },
  { "turn off"      , A_DEACTIVATE   },
  { "turn on"       , A_ACTIVATE     },
  { "walk through"  , A_CLIMBTHROUGH },
  { "what is"       , A_EXAMINE      },
  { "wind up"       , A_WIND         },

  //one word

  { "acquire"       , A_TAKE         },
  { "activate"      , A_ACTIVATE     },
  { "advance"       , A_GO           },
  { "ascend"        , A_CLIMBUP      },
  { "attach"        , A_TIE          },
  { "attack"        , A_ATTACK       },
  { "bathe"         , A_SWIM         },
  { "bite"          , A_EAT          },
  { "board"         , A_ENTER        },
  { "brandish"      , A_WAVE         },
  { "break"         , A_BREAK        },
  { "brief"         , A_BRIEF        },
  { "burn"          , A_ACTIVATE     },
  { "carry"         , A_TAKE         },
  { "catch"         , A_TAKE         },
  { "climb"         , A_CLIMB        },
  { "close"         , A_CLOSE        },
  { "consume"       , A_EAT          },
  { "count"         , A_COUNT        },
  { "d"             , A_DOWN         },
  { "damage"        , A_BREAK        },
  { "deactivate"    , A_DEACTIVATE   },
  { "deflate"       , A_DEFLATE      },
  { "descend"       , A_CLIMBDOWN    },
  { "describe"      , A_EXAMINE      },
  { "destroy"       , A_BREAK        },
  { "diagnose"      , A_DIAGNOSE     },
  { "dig"           , A_DIG          },
  { "discard"       , A_DROP         },
  { "disembark"     , A_DISEMBARK    },
  { "dislodge"      , A_MOVE         },
  { "dispatch"      , A_ATTACK       },
  { "donate"        , A_GIVE         },
  { "down"          , A_DOWN         },
  { "douse"         , A_DEACTIVATE   },
  { "drink"         , A_DRINK        },
  { "drop"          , A_DROP         },
  { "e"             , A_EAST         },
  { "east"          , A_EAST         },
  { "eat"           , A_EAT          },
  { "echo"          , A_ECHO         },
  { "empty"         , A_EMPTY        },
  { "enter"         , A_ENTER        },
  { "examine"       , A_EXAMINE      },
  { "excavate"      , A_DIG          },
  { "exit"          , A_EXIT         },
  { "extinguish"    , A_DEACTIVATE   },
  { "fasten"        , A_TIE          },
  { "feed"          , A_GIVE         },
  { "feel"          , A_TOUCH        },
  { "fight"         , A_ATTACK       },
  { "fill"          , A_FILL         },
  { "fix"           , A_FIX          },
  { "flick"         , A_ACTIVATE     },
  { "flip"          , A_ACTIVATE     },
  { "free"          , A_UNTIE        },
  { "gaze"          , A_LOOK         },
  { "get"           , A_TAKE         },
  { "give"          , A_GIVE         },
  { "glue"          , A_FIX          },
  { "go"            , A_GO           },
  { "grab"          , A_TAKE         },
  { "grease"        , A_OIL          },
  { "head"          , A_GO           },
  { "hide"          , A_PUT          },
  { "hit"           , A_ATTACK       },
  { "hold"          , A_TAKE         },
  { "hurt"          , A_ATTACK       },
  { "i"             , A_INVENTORY    },
  { "ignite"        , A_ACTIVATE     },
  { "imbibe"        , A_DRINK        },
  { "in"            , A_IN           },
  { "incinerate"    , A_ACTIVATE     },
  { "inflate"       , A_INFLATE      },
  { "injure"        , A_ATTACK       },
  { "insert"        , A_PUT          },
  { "inspect"       , A_EXAMINE      },
  { "inventory"     , A_INVENTORY    },
  { "journey"       , A_GO           },
  { "jump"          , A_JUMP         },
  { "kill"          , A_ATTACK       },
  { "knock"         , A_KNOCK        },
  { "l"             , A_LOOK         },
  { "land"          , A_LAND         },
  { "launch"        , A_LAUNCH       },
  { "leap"          , A_JUMP         },
  { "leave"         , A_EXIT         },
  { "lift"          , A_RAISE        },
  { "light"         , A_ACTIVATE     },
  { "lock"          , A_LOCK         },
  { "look"          , A_LOOK         },
  { "loosen"        , A_MOVE         },
  { "lower"         , A_LOWER        },
  { "lubricate"     , A_OIL          },
  { "mount"         , A_MOUNT        },
  { "move"          , A_MOVE         },
  { "murder"        , A_ATTACK       },
  { "n"             , A_NORTH        },
  { "ne"            , A_NORTHEAST    },
  { "north"         , A_NORTH        },
  { "northeast"     , A_NORTHEAST    },
  { "northwest"     , A_NORTHWEST    },
  { "nw"            , A_NORTHWEST    },
  { "obtain"        , A_TAKE         },
  { "odysseus"      , A_ODYSSEUS     },
  { "offer"         , A_GIVE         },
  { "oil"           , A_OIL          },
  { "open"          , A_OPEN         },
  { "out"           , A_OUT          },
  { "pat"           , A_TOUCH        },
  { "patch"         , A_FIX          },
  { "peal"          , A_RING         },
  { "pet"           , A_TOUCH        },
  { "place"         , A_PUT          },
  { "play"          , A_PLAY         },
  { "plug"          , A_FIX          },
  { "pray"          , A_PRAY         },
  { "press"         , A_PUSH         },
  { "proceed"       , A_GO           },
  { "pry"           , A_PRY          },
  { "pull"          , A_PULL         },
  { "pump"          , A_INFLATE      },
  { "push"          , A_PUSH         },
  { "put"           , A_PUT          },
  { "q"             , A_QUIT         },
  { "quit"          , A_QUIT         },
  { "raise"         , A_RAISE        },
  { "read"          , A_READ         },
  { "release"       , A_UNTIE        },
  { "remove"        , A_REMOVE       },
  { "repair"        , A_FIX          },
  { "restart"       , A_RESTART      },
  { "restore"       , A_RESTORE      },
  { "ring"          , A_RING         },
  { "rotate"        , A_TURN         },
  { "rub"           , A_TOUCH        },
  { "run"           , A_GO           },
  { "s"             , A_SOUTH        },
  { "save"          , A_SAVE         },
  { "score"         , A_SCORE        },
  { "se"            , A_SOUTHEAST    },
  { "secure"        , A_TIE          },
  { "set"           , A_PUT          },
  { "shut"          , A_CLOSE        },
  { "skim"          , A_READ         },
  { "slay"          , A_ATTACK       },
  { "sleep"         , A_SLEEP        },
  { "smash"         , A_BREAK        },
  { "south"         , A_SOUTH        },
  { "southeast"     , A_SOUTHEAST    },
  { "southwest"     , A_SOUTHWEST    },
  { "spin"          , A_TURN         },
  { "squeeze"       , A_SQUEEZE      },
  { "stab"          , A_ATTACK       },
  { "stand"         , A_DISEMBARK    },
  { "stare"         , A_LOOK         },
  { "step"          , A_GO           },
  { "stop"          , A_FIX          },
  { "strike"        , A_ATTACK       },
  { "stuff"         , A_PUT          },
  { "superbrief"    , A_SUPERBRIEF   },
  { "sw"            , A_SOUTHWEST    },
  { "swallow"       , A_DRINK        },
  { "swim"          , A_SWIM         },
  { "swing"         , A_WAVE         },
  { "take"          , A_TAKE         },
  { "taste"         , A_EAT          },
  { "thrust"        , A_WAVE         },
  { "tie"           , A_TIE          },
  { "touch"         , A_TOUCH        },
  { "travel"        , A_GO           },
  { "turn"          , A_TURN         },
  { "u"             , A_UP           },
  { "ulysses"       , A_ODYSSEUS     },
  { "unattach"      , A_UNTIE        },
  { "unfasten"      , A_UNTIE        },
  { "unhook"        , A_UNTIE        },
  { "unlock"        , A_UNLOCK       },
  { "untie"         , A_UNTIE        },
  { "up"            , A_UP           },
  { "verbose"       , A_VERBOSE      },
  { "version"       , A_VERSION      },
  { "w"             , A_WEST         },
  { "wade"          , A_SWIM         },
  { "wait"          , A_WAIT         },
  { "walk"          , A_GO           },
  { "wave"          , A_WAVE         },
  { "wear"          , A_WEAR         },
  { "west"          , A_WEST         },
  { "what"          , A_EXAMINE      },
  { "what's"        , A_EXAMINE      },
  { "wind"          , A_WIND         },
  { "x"             , A_EXAMINE      },
  { "z"             , A_WAIT         },

  {0, 0}
};



//phrase must contain a maximum of three words

//for matching to work, phrases must be listed in order of decreasing word size

//different objects can have the same phrase, but there must
//be larger phrases for them, so player can be more specific when needed

//words must be separated by exactly one space

//NOTE: if there is a phrase like "disk drive" and then phrases "disk" and drive",
//which represent two different objects, parser will ask player to be more specific,
//so it is best to avoid "disk drive" and use something like "storage drive"


// objects that have same phrase as fixed objects:
//   water

// objects that have same phrase but won't prompt player to be specific
// because they won't exist in same room at same time:
//   basket                                                (raised and lowered)
//   brass bell  bell                                      (cool and hot)
//   lantern  lamp                                         (unbroken and broken)
//   boat                                                  (uninflated, inflated, punctured)
//   large egg  jewel-encrusted egg  egg                   (unbroken and broken)
//   golden canary  gold canary  clockwork canary  canary  (unbroken and broken)

// objects that have same phrase and will prompt player to be specific
// if they are in same room at same time:
//   lantern  lamp                                         (unbroken/broken and burned-out)
//   bag                                                   (sandwich bag, bag of coins, large bag)
//   knife                                                 (nasty and rusty)
//   pile                                                  (leaves, uninflated boat, coal)
//   book                                                  (black and guide)

struct NOUNPHRASETOOBJ_STRUCT NounPhraseToObj[] =
{
  { "me"                          , OBJ_YOU                },
  { "myself"                      , OBJ_YOU                },
  { "self"                        , OBJ_YOU                },
  { "bare hands"                  , OBJ_YOU                },
  { "my hands"                    , OBJ_YOU                },
  { "my hand"                     , OBJ_YOU                },
  { "hands"                       , OBJ_YOU                },
  { "hand"                        , OBJ_YOU                },
  { "cyclops"                     , OBJ_CYCLOPS            },
  { "evil spirits"                , OBJ_GHOSTS             },
  { "spirits"                     , OBJ_GHOSTS             },
  { "spirit"                      , OBJ_GHOSTS             },
  { "ghosts"                      , OBJ_GHOSTS             },
  { "ghost"                       , OBJ_GHOSTS             },
  { "vampire bat"                 , OBJ_BAT                },
  { "bat"                         , OBJ_BAT                },
  { "individual"                  , OBJ_THIEF              },
  { "man"                         , OBJ_THIEF              },
  { "person"                      , OBJ_THIEF              },
  { "thief"                       , OBJ_THIEF              },
  { "robber"                      , OBJ_THIEF              },
  { "nasty troll"                 , OBJ_TROLL              },
  { "troll"                       , OBJ_TROLL              },
  { "basket"                      , OBJ_LOWERED_BASKET     },
  { "basket"                      , OBJ_RAISED_BASKET      },
  { "trophy case"                 , OBJ_TROPHY_CASE        },
  { "case"                        , OBJ_TROPHY_CASE        },
  { "machine"                     , OBJ_MACHINE            },
  { "lid"                         , OBJ_MACHINE            },
  { "small mailbox"               , OBJ_MAILBOX            },
  { "mailbox"                     , OBJ_MAILBOX            },
  { "box"                         , OBJ_MAILBOX            },
  { "quantity of water"           , OBJ_WATER              },
  { "water"                       , OBJ_WATER              },
  { "crystal skull"               , OBJ_SKULL              },
  { "skull"                       , OBJ_SKULL              },
  { "broken timber"               , OBJ_TIMBERS            },
  { "timber"                      , OBJ_TIMBERS            },
  { "hot pepper sandwich"         , OBJ_LUNCH              },
  { "pepper sandwich"             , OBJ_LUNCH              },
  { "sandwich"                    , OBJ_LUNCH              },
  { "lunch"                       , OBJ_LUNCH              },
  { "brass bell"                  , OBJ_BELL               },
  { "bell"                        , OBJ_BELL               },
  { "red hot bell"                , OBJ_HOT_BELL           },
  { "hot brass bell"              , OBJ_HOT_BELL           },
  { "hot bell"                    , OBJ_HOT_BELL           },
  { "brass bell"                  , OBJ_HOT_BELL           },
  { "bell"                        , OBJ_HOT_BELL           },
  { "large book"                  , OBJ_BOOK               },
  { "black book"                  , OBJ_BOOK               },
  { "book"                        , OBJ_BOOK               },
  { "page"                        , OBJ_BOOK               },
  { "bloody axe"                  , OBJ_AXE                },
  { "bloody ax"                   , OBJ_AXE                },
  { "axe"                         , OBJ_AXE                },
  { "ax"                          , OBJ_AXE                },
  { "broken lantern"              , OBJ_BROKEN_LAMP        },
  { "broken lamp"                 , OBJ_BROKEN_LAMP        },
  { "lantern"                     , OBJ_BROKEN_LAMP        },
  { "lamp"                        , OBJ_BROKEN_LAMP        },
  { "ornamented sceptre"          , OBJ_SCEPTRE            },
  { "ornamented scepter"          , OBJ_SCEPTRE            },
  { "sceptre"                     , OBJ_SCEPTRE            },
  { "scepter"                     , OBJ_SCEPTRE            },
  { "elongated sack"              , OBJ_SANDWICH_BAG       },
  { "brown sack"                  , OBJ_SANDWICH_BAG       },
  { "elongated bag"               , OBJ_SANDWICH_BAG       },
  { "brown bag"                   , OBJ_SANDWICH_BAG       },
  { "sack"                        , OBJ_SANDWICH_BAG       },
  { "bag"                         , OBJ_SANDWICH_BAG       },
  { "engraved chalice"            , OBJ_CHALICE            },
  { "silver chalice"              , OBJ_CHALICE            },
  { "chalice"                     , OBJ_CHALICE            },
  { "clove of garlic"             , OBJ_GARLIC             },
  { "clove"                       , OBJ_GARLIC             },
  { "garlic"                      , OBJ_GARLIC             },
  { "crystal trident"             , OBJ_TRIDENT            },
  { "trident"                     , OBJ_TRIDENT            },
  { "glass bottle"                , OBJ_BOTTLE             },
  { "bottle"                      , OBJ_BOTTLE             },
  { "solid-gold coffin"           , OBJ_COFFIN             },
  { "gold coffin"                 , OBJ_COFFIN             },
  { "coffin"                      , OBJ_COFFIN             },
  { "hand-held pump"              , OBJ_PUMP               },
  { "air pump"                    , OBJ_PUMP               },
  { "pump"                        , OBJ_PUMP               },
  { "huge diamond"                , OBJ_DIAMOND            },
  { "enormous diamond"            , OBJ_DIAMOND            },
  { "diamond"                     , OBJ_DIAMOND            },
  { "exquisite figurine"          , OBJ_JADE               },
  { "jade figurine"               , OBJ_JADE               },
  { "figurine"                    , OBJ_JADE               },
  { "nasty-looking knife"         , OBJ_KNIFE              },
  { "nasty knife"                 , OBJ_KNIFE              },
  { "knife"                       , OBJ_KNIFE              },
  { "burned-out lantern"          , OBJ_BURNED_OUT_LANTERN },
  { "burned-out lamp"             , OBJ_BURNED_OUT_LANTERN },
  { "useless lantern"             , OBJ_BURNED_OUT_LANTERN },
  { "useless lamp"                , OBJ_BURNED_OUT_LANTERN },
  { "lantern"                     , OBJ_BURNED_OUT_LANTERN },
  { "lamp"                        , OBJ_BURNED_OUT_LANTERN },
  { "bag of coins"                , OBJ_BAG_OF_COINS       },
  { "leather bag"                 , OBJ_BAG_OF_COINS       },
  { "bag"                         , OBJ_BAG_OF_COINS       },
  { "coins"                       , OBJ_BAG_OF_COINS       },
  { "brass lantern"               , OBJ_LAMP               },
  { "brass lamp"                  , OBJ_LAMP               },
  { "lantern"                     , OBJ_LAMP               },
  { "lamp"                        , OBJ_LAMP               },
  { "light"                       , OBJ_LAMP               },
  { "large emerald"               , OBJ_EMERALD            },
  { "emerald"                     , OBJ_EMERALD            },
  { "small leaflet"               , OBJ_ADVERTISEMENT      },
  { "leaflet"                     , OBJ_ADVERTISEMENT      },
  { "mail"                        , OBJ_ADVERTISEMENT      },
  { "magic boat"                  , OBJ_INFLATED_BOAT      },
  { "inflated boat"               , OBJ_INFLATED_BOAT      },
  { "boat"                        , OBJ_INFLATED_BOAT      },
  { "match"                       , OBJ_MATCH              },
  { "matches"                     , OBJ_MATCH              },
  { "matchbook"                   , OBJ_MATCH              },
  { "beautiful painting"          , OBJ_PAINTING           },
  { "painting"                    , OBJ_PAINTING           },
  { "pair of candles"             , OBJ_CANDLES            },
  { "candles"                     , OBJ_CANDLES            },
  { "piece of slag"               , OBJ_GUNK               },
  { "vitreous slag"               , OBJ_GUNK               },
  { "slag"                        , OBJ_GUNK               },
  { "pile of leaves"              , OBJ_LEAVES             },
  { "leaves"                      , OBJ_LEAVES             },
  { "pile"                        , OBJ_LEAVES             },
  { "punctured boat"              , OBJ_PUNCTURED_BOAT     },
  { "boat"                        , OBJ_PUNCTURED_BOAT     },
  { "pile of plastic"             , OBJ_INFLATABLE_BOAT    },
  { "inflatable boat"             , OBJ_INFLATABLE_BOAT    },
  { "plastic"                     , OBJ_INFLATABLE_BOAT    },
  { "pile"                        , OBJ_INFLATABLE_BOAT    },
  { "boat"                        , OBJ_INFLATABLE_BOAT    },
  { "valve"                       , OBJ_INFLATABLE_BOAT    },
  { "bar of platinum"             , OBJ_BAR                },
  { "large bar"                   , OBJ_BAR                },
  { "platinum bar"                , OBJ_BAR                },
  { "bar"                         , OBJ_BAR                },
  { "pot of gold"                 , OBJ_POT_OF_GOLD        },
  { "pot"                         , OBJ_POT_OF_GOLD        },
  { "gold"                        , OBJ_POT_OF_GOLD        },
  { "red buoy"                    , OBJ_BUOY               },
  { "buoy"                        , OBJ_BUOY               },
  { "coil of rope"                , OBJ_ROPE               },
  { "coil"                        , OBJ_ROPE               },
  { "rope"                        , OBJ_ROPE               },
  { "rusty knife"                 , OBJ_RUSTY_KNIFE        },
  { "knife"                       , OBJ_RUSTY_KNIFE        },
  { "sapphire-encrusted bracelet" , OBJ_BRACELET           },
  { "sapphire bracelet"           , OBJ_BRACELET           },
  { "bracelet"                    , OBJ_BRACELET           },
  { "tool chests"                 , OBJ_TOOL_CHEST         },
  { "tool chest"                  , OBJ_TOOL_CHEST         },
  { "chests"                      , OBJ_TOOL_CHEST         },
  { "chest"                       , OBJ_TOOL_CHEST         },
  { "screwdriver"                 , OBJ_SCREWDRIVER        },
  { "skeleton key"                , OBJ_KEYS               },
  { "key"                         , OBJ_KEYS               },
  { "shovel"                      , OBJ_SHOVEL             },
  { "pile of coal"                , OBJ_COAL               },
  { "small pile"                  , OBJ_COAL               },
  { "pile"                        , OBJ_COAL               },
  { "coal"                        , OBJ_COAL               },
  { "beautiful scarab"            , OBJ_SCARAB             },
  { "jeweled scarab"              , OBJ_SCARAB             },
  { "scarab"                      , OBJ_SCARAB             },
  { "large bag"                   , OBJ_LARGE_BAG          },
  { "bag"                         , OBJ_LARGE_BAG          },
  { "vicious stiletto"            , OBJ_STILETTO           },
  { "stiletto"                    , OBJ_STILETTO           },
  { "elvish sword"                , OBJ_SWORD              },
  { "antique sword"               , OBJ_SWORD              },
  { "sword"                       , OBJ_SWORD              },
  { "ancient map"                 , OBJ_MAP                },
  { "ancient parchment"           , OBJ_MAP                },
  { "parchment map"               , OBJ_MAP                },
  { "map"                         , OBJ_MAP                },
  { "parchment"                   , OBJ_MAP                },
  { "tan label"                   , OBJ_BOAT_LABEL         },
  { "label"                       , OBJ_BOAT_LABEL         },
  { "ivory torch"                 , OBJ_TORCH              },
  { "torch"                       , OBJ_TORCH              },
  { "tour guidebook"              , OBJ_GUIDE              },
  { "tour guide"                  , OBJ_GUIDE              },
  { "guide book"                  , OBJ_GUIDE              },
  { "guidebook"                   , OBJ_GUIDE              },
  { "guide"                       , OBJ_GUIDE              },
  { "book"                        , OBJ_GUIDE              },
  { "trunk of jewels"             , OBJ_TRUNK              },
  { "old trunk"                   , OBJ_TRUNK              },
  { "trunk"                       , OBJ_TRUNK              },
  { "jewels"                      , OBJ_TRUNK              },
  { "tube of toothpaste"          , OBJ_TUBE               },
  { "toothpaste tube"             , OBJ_TUBE               },
  { "toothpaste"                  , OBJ_TUBE               },
  { "tube"                        , OBJ_TUBE               },
  { "viscous material"            , OBJ_PUTTY              },
  { "material"                    , OBJ_PUTTY              },
  { "gunk"                        , OBJ_PUTTY              },
  { "piece of paper"              , OBJ_OWNERS_MANUAL      },
  { "zork manual"                 , OBJ_OWNERS_MANUAL      },
  { "owner's manual"              , OBJ_OWNERS_MANUAL      },
  { "manual"                      , OBJ_OWNERS_MANUAL      },
  { "paper"                       , OBJ_OWNERS_MANUAL      },
  { "wrench"                      , OBJ_WRENCH             },
  { "small nest"                  , OBJ_NEST               },
  { "bird's nest"                 , OBJ_NEST               },
  { "bird nest"                   , OBJ_NEST               },
  { "nest"                        , OBJ_NEST               },
  { "large egg"                   , OBJ_EGG                },
  { "jewel-encrusted egg"         , OBJ_EGG                },
  { "egg"                         , OBJ_EGG                },
  { "broken egg"                  , OBJ_BROKEN_EGG         },
  { "ruined egg"                  , OBJ_BROKEN_EGG         },
  { "large egg"                   , OBJ_BROKEN_EGG         },
  { "jewel-encrusted egg"         , OBJ_BROKEN_EGG         },
  { "egg"                         , OBJ_BROKEN_EGG         },
  { "beautiful bauble"            , OBJ_BAUBLE             },
  { "brass bauble"                , OBJ_BAUBLE             },
  { "bauble"                      , OBJ_BAUBLE             },
  { "golden canary"               , OBJ_CANARY             },
  { "gold canary"                 , OBJ_CANARY             },
  { "clockwork canary"            , OBJ_CANARY             },
  { "canary"                      , OBJ_CANARY             },
  { "broken canary"               , OBJ_BROKEN_CANARY      },
  { "golden canary"               , OBJ_BROKEN_CANARY      },
  { "gold canary"                 , OBJ_BROKEN_CANARY      },
  { "clockwork canary"            , OBJ_BROKEN_CANARY      },
  { "canary"                      , OBJ_BROKEN_CANARY      },
  { "old engravings"              , OBJ_ENGRAVINGS         },
  { "old engraving"               , OBJ_ENGRAVINGS         },
  { "engravings"                  , OBJ_ENGRAVINGS         },
  { "engraving"                   , OBJ_ENGRAVINGS         },

  { 0 , 0 }
};



// single words that refer to multiple objects:
//   window  cliff  door  table  button

// two-word noun phrases must come before one-word, for matching to work properly

struct NOUNPHRASETOFIXEDOBJ_STRUCT NounPhraseToFixedObj[] =
{
  { "steep slide"          , ROOM_CELLAR              , FOBJ_SLIDE           },
  { "steep slide"          , ROOM_SLIDE_ROOM          , FOBJ_SLIDE           },
  { "metal slide"          , ROOM_CELLAR              , FOBJ_SLIDE           },
  { "metal slide"          , ROOM_SLIDE_ROOM          , FOBJ_SLIDE           },
  { "steep ramp"           , ROOM_CELLAR              , FOBJ_SLIDE           },
  { "steep ramp"           , ROOM_SLIDE_ROOM          , FOBJ_SLIDE           },
  { "metal ramp"           , ROOM_CELLAR              , FOBJ_SLIDE           },
  { "metal ramp"           , ROOM_SLIDE_ROOM          , FOBJ_SLIDE           },
  { "slide"                , ROOM_CELLAR              , FOBJ_SLIDE           },
  { "slide"                , ROOM_SLIDE_ROOM          , FOBJ_SLIDE           },
  { "ramp"                 , ROOM_CELLAR              , FOBJ_SLIDE           },
  { "ramp"                 , ROOM_SLIDE_ROOM          , FOBJ_SLIDE           },
  { "boards"               , ROOM_WEST_OF_HOUSE       , FOBJ_BOARD           },
  { "boards"               , ROOM_NORTH_OF_HOUSE      , FOBJ_BOARD           },
  { "boards"               , ROOM_SOUTH_OF_HOUSE      , FOBJ_BOARD           },
  { "board"                , ROOM_WEST_OF_HOUSE       , FOBJ_BOARD           },
  { "board"                , ROOM_NORTH_OF_HOUSE      , FOBJ_BOARD           },
  { "board"                , ROOM_SOUTH_OF_HOUSE      , FOBJ_BOARD           },
  { "song bird"            , ROOM_FOREST_1            , FOBJ_SONGBIRD        },
  { "song bird"            , ROOM_FOREST_2            , FOBJ_SONGBIRD        },
  { "song bird"            , ROOM_FOREST_3            , FOBJ_SONGBIRD        },
  { "song bird"            , ROOM_PATH                , FOBJ_SONGBIRD        },
  { "song bird"            , ROOM_UP_A_TREE           , FOBJ_SONGBIRD        },
  { "song bird"            , ROOM_CLEARING            , FOBJ_SONGBIRD        },
  { "songbird"             , ROOM_FOREST_1            , FOBJ_SONGBIRD        },
  { "songbird"             , ROOM_FOREST_2            , FOBJ_SONGBIRD        },
  { "songbird"             , ROOM_FOREST_3            , FOBJ_SONGBIRD        },
  { "songbird"             , ROOM_PATH                , FOBJ_SONGBIRD        },
  { "songbird"             , ROOM_UP_A_TREE           , FOBJ_SONGBIRD        },
  { "songbird"             , ROOM_CLEARING            , FOBJ_SONGBIRD        },
  { "bird"                 , ROOM_FOREST_1            , FOBJ_SONGBIRD        },
  { "bird"                 , ROOM_FOREST_2            , FOBJ_SONGBIRD        },
  { "bird"                 , ROOM_FOREST_3            , FOBJ_SONGBIRD        },
  { "bird"                 , ROOM_PATH                , FOBJ_SONGBIRD        },
  { "bird"                 , ROOM_UP_A_TREE           , FOBJ_SONGBIRD        },
  { "bird"                 , ROOM_CLEARING            , FOBJ_SONGBIRD        },
  { "white house"          , ROOM_WEST_OF_HOUSE       , FOBJ_WHITE_HOUSE     },
  { "white house"          , ROOM_NORTH_OF_HOUSE      , FOBJ_WHITE_HOUSE     },
  { "white house"          , ROOM_SOUTH_OF_HOUSE      , FOBJ_WHITE_HOUSE     },
  { "white house"          , ROOM_EAST_OF_HOUSE       , FOBJ_WHITE_HOUSE     },
  { "white house"          , ROOM_FOREST_1            , FOBJ_WHITE_HOUSE     },
  { "white house"          , ROOM_FOREST_2            , FOBJ_WHITE_HOUSE     },
  { "white house"          , ROOM_MOUNTAINS           , FOBJ_WHITE_HOUSE     },
  { "white house"          , ROOM_FOREST_3            , FOBJ_WHITE_HOUSE     },
  { "white house"          , ROOM_PATH                , FOBJ_WHITE_HOUSE     },
  { "white house"          , ROOM_UP_A_TREE           , FOBJ_WHITE_HOUSE     },
  { "white house"          , ROOM_GRATING_CLEARING    , FOBJ_WHITE_HOUSE     },
  { "white house"          , ROOM_CLEARING            , FOBJ_WHITE_HOUSE     },
  { "house"                , ROOM_WEST_OF_HOUSE       , FOBJ_WHITE_HOUSE     },
  { "house"                , ROOM_NORTH_OF_HOUSE      , FOBJ_WHITE_HOUSE     },
  { "house"                , ROOM_SOUTH_OF_HOUSE      , FOBJ_WHITE_HOUSE     },
  { "house"                , ROOM_EAST_OF_HOUSE       , FOBJ_WHITE_HOUSE     },
  { "house"                , ROOM_FOREST_1            , FOBJ_WHITE_HOUSE     },
  { "house"                , ROOM_FOREST_2            , FOBJ_WHITE_HOUSE     },
  { "house"                , ROOM_MOUNTAINS           , FOBJ_WHITE_HOUSE     },
  { "house"                , ROOM_FOREST_3            , FOBJ_WHITE_HOUSE     },
  { "house"                , ROOM_PATH                , FOBJ_WHITE_HOUSE     },
  { "house"                , ROOM_UP_A_TREE           , FOBJ_WHITE_HOUSE     },
  { "house"                , ROOM_GRATING_CLEARING    , FOBJ_WHITE_HOUSE     },
  { "house"                , ROOM_CLEARING            , FOBJ_WHITE_HOUSE     },
  { "forest"               , ROOM_WEST_OF_HOUSE       , FOBJ_FOREST          },
  { "forest"               , ROOM_NORTH_OF_HOUSE      , FOBJ_FOREST          },
  { "forest"               , ROOM_SOUTH_OF_HOUSE      , FOBJ_FOREST          },
  { "forest"               , ROOM_EAST_OF_HOUSE       , FOBJ_FOREST          },
  { "forest"               , ROOM_FOREST_1            , FOBJ_FOREST          },
  { "forest"               , ROOM_FOREST_2            , FOBJ_FOREST          },
  { "forest"               , ROOM_FOREST_3            , FOBJ_FOREST          },
  { "forest"               , ROOM_PATH                , FOBJ_FOREST          },
  { "forest"               , ROOM_UP_A_TREE           , FOBJ_FOREST          },
  { "forest"               , ROOM_CLEARING            , FOBJ_FOREST          },
  { "trees"                , ROOM_WEST_OF_HOUSE       , FOBJ_FOREST          },
  { "trees"                , ROOM_NORTH_OF_HOUSE      , FOBJ_FOREST          },
  { "trees"                , ROOM_SOUTH_OF_HOUSE      , FOBJ_FOREST          },
  { "trees"                , ROOM_EAST_OF_HOUSE       , FOBJ_FOREST          },
  { "trees"                , ROOM_FOREST_1            , FOBJ_FOREST          },
  { "trees"                , ROOM_FOREST_2            , FOBJ_FOREST          },
  { "trees"                , ROOM_FOREST_3            , FOBJ_FOREST          },
  { "trees"                , ROOM_PATH                , FOBJ_FOREST          },
  { "trees"                , ROOM_UP_A_TREE           , FOBJ_FOREST          },
  { "trees"                , ROOM_CLEARING            , FOBJ_FOREST          },
  { "large tree"           , ROOM_FOREST_1            , FOBJ_TREE            },
  { "large tree"           , ROOM_FOREST_2            , FOBJ_TREE            },
  { "large tree"           , ROOM_MOUNTAINS           , FOBJ_TREE            },
  { "large tree"           , ROOM_FOREST_3            , FOBJ_TREE            },
  { "large tree"           , ROOM_PATH                , FOBJ_TREE            },
  { "large tree"           , ROOM_UP_A_TREE           , FOBJ_TREE            },
  { "large tree"           , ROOM_CLEARING            , FOBJ_TREE            },
  { "tree"                 , ROOM_FOREST_1            , FOBJ_TREE            },
  { "tree"                 , ROOM_FOREST_2            , FOBJ_TREE            },
  { "tree"                 , ROOM_MOUNTAINS           , FOBJ_TREE            },
  { "tree"                 , ROOM_FOREST_3            , FOBJ_TREE            },
  { "tree"                 , ROOM_PATH                , FOBJ_TREE            },
  { "tree"                 , ROOM_UP_A_TREE           , FOBJ_TREE            },
  { "tree"                 , ROOM_CLEARING            , FOBJ_TREE            },
  { "small window"         , ROOM_EAST_OF_HOUSE       , FOBJ_KITCHEN_WINDOW  },
  { "small window"         , ROOM_KITCHEN             , FOBJ_KITCHEN_WINDOW  },
  { "kitchen window"       , ROOM_EAST_OF_HOUSE       , FOBJ_KITCHEN_WINDOW  },
  { "kitchen window"       , ROOM_KITCHEN             , FOBJ_KITCHEN_WINDOW  },
  { "window"               , ROOM_EAST_OF_HOUSE       , FOBJ_KITCHEN_WINDOW  },
  { "window"               , ROOM_KITCHEN             , FOBJ_KITCHEN_WINDOW  },
  { "dark chimney"         , ROOM_KITCHEN             , FOBJ_CHIMNEY         },
  { "dark chimney"         , ROOM_STUDIO              , FOBJ_CHIMNEY         },
  { "narrow chimney"       , ROOM_KITCHEN             , FOBJ_CHIMNEY         },
  { "narrow chimney"       , ROOM_STUDIO              , FOBJ_CHIMNEY         },
  { "chimney"              , ROOM_KITCHEN             , FOBJ_CHIMNEY         },
  { "chimney"              , ROOM_STUDIO              , FOBJ_CHIMNEY         },
  { "boarded window"       , ROOM_NORTH_OF_HOUSE      , FOBJ_BOARDED_WINDOW  },
  { "boarded window"       , ROOM_SOUTH_OF_HOUSE      , FOBJ_BOARDED_WINDOW  },
  { "window"               , ROOM_NORTH_OF_HOUSE      , FOBJ_BOARDED_WINDOW  },
  { "window"               , ROOM_SOUTH_OF_HOUSE      , FOBJ_BOARDED_WINDOW  },
  { "narrow crack"         , ROOM_DAMP_CAVE           , FOBJ_CRACK           },
  { "narrow crack"         , ROOM_CHASM_ROOM          , FOBJ_CRACK           },
  { "crack"                , ROOM_DAMP_CAVE           , FOBJ_CRACK           },
  { "crack"                , ROOM_CHASM_ROOM          , FOBJ_CRACK           },
  { "grate"                , ROOM_GRATING_CLEARING    , FOBJ_GRATE           },
  { "grate"                , ROOM_GRATING_ROOM        , FOBJ_GRATE           },
  { "grating"              , ROOM_GRATING_CLEARING    , FOBJ_GRATE           },
  { "grating"              , ROOM_GRATING_ROOM        , FOBJ_GRATE           },
  { "rocky ledge"          , ROOM_CANYON_BOTTOM       , FOBJ_CLIMBABLE_CLIFF },
  { "rocky ledge"          , ROOM_CLIFF_MIDDLE        , FOBJ_CLIMBABLE_CLIFF },
  { "rocky ledge"          , ROOM_CANYON_VIEW         , FOBJ_CLIMBABLE_CLIFF },
  { "rocky cliff"          , ROOM_CANYON_BOTTOM       , FOBJ_CLIMBABLE_CLIFF },
  { "rocky cliff"          , ROOM_CLIFF_MIDDLE        , FOBJ_CLIMBABLE_CLIFF },
  { "rocky cliff"          , ROOM_CANYON_VIEW         , FOBJ_CLIMBABLE_CLIFF },
  { "ledge"                , ROOM_CANYON_BOTTOM       , FOBJ_CLIMBABLE_CLIFF },
  { "ledge"                , ROOM_CLIFF_MIDDLE        , FOBJ_CLIMBABLE_CLIFF },
  { "ledge"                , ROOM_CANYON_VIEW         , FOBJ_CLIMBABLE_CLIFF },
  { "cliff"                , ROOM_CANYON_BOTTOM       , FOBJ_CLIMBABLE_CLIFF },
  { "cliff"                , ROOM_CLIFF_MIDDLE        , FOBJ_CLIMBABLE_CLIFF },
  { "cliff"                , ROOM_CANYON_VIEW         , FOBJ_CLIMBABLE_CLIFF },
  { "white cliff"          , ROOM_WHITE_CLIFFS_NORTH  , FOBJ_WHITE_CLIFF     },
  { "white cliff"          , ROOM_WHITE_CLIFFS_SOUTH  , FOBJ_WHITE_CLIFF     },
  { "white cliffs"         , ROOM_WHITE_CLIFFS_NORTH  , FOBJ_WHITE_CLIFF     },
  { "white cliffs"         , ROOM_WHITE_CLIFFS_SOUTH  , FOBJ_WHITE_CLIFF     },
  { "cliff"                , ROOM_WHITE_CLIFFS_NORTH  , FOBJ_WHITE_CLIFF     },
  { "cliff"                , ROOM_WHITE_CLIFFS_SOUTH  , FOBJ_WHITE_CLIFF     },
  { "cliffs"               , ROOM_WHITE_CLIFFS_NORTH  , FOBJ_WHITE_CLIFF     },
  { "cliffs"               , ROOM_WHITE_CLIFFS_SOUTH  , FOBJ_WHITE_CLIFF     },
  { "mangled bodies"       , ROOM_ENTRANCE_TO_HADES   , FOBJ_BODIES          },
  { "mangled bodies"       , ROOM_LAND_OF_LIVING_DEAD , FOBJ_BODIES          },
  { "bodies"               , ROOM_ENTRANCE_TO_HADES   , FOBJ_BODIES          },
  { "bodies"               , ROOM_LAND_OF_LIVING_DEAD , FOBJ_BODIES          },
  { "rainbow"              , ROOM_ARAGAIN_FALLS       , FOBJ_RAINBOW         },
  { "rainbow"              , ROOM_ON_RAINBOW          , FOBJ_RAINBOW         },
  { "rainbow"              , ROOM_END_OF_RAINBOW      , FOBJ_RAINBOW         },
  { "rainbow"              , ROOM_CANYON_VIEW         , FOBJ_RAINBOW         },
  { "frigid river"         , ROOM_DAM_BASE            , FOBJ_RIVER           },
  { "frigid river"         , ROOM_RIVER_1             , FOBJ_RIVER           },
  { "frigid river"         , ROOM_RIVER_2             , FOBJ_RIVER           },
  { "frigid river"         , ROOM_RIVER_3             , FOBJ_RIVER           },
  { "frigid river"         , ROOM_WHITE_CLIFFS_NORTH  , FOBJ_RIVER           },
  { "frigid river"         , ROOM_WHITE_CLIFFS_SOUTH  , FOBJ_RIVER           },
  { "frigid river"         , ROOM_RIVER_4             , FOBJ_RIVER           },
  { "frigid river"         , ROOM_RIVER_5             , FOBJ_RIVER           },
  { "frigid river"         , ROOM_SHORE               , FOBJ_RIVER           },
  { "frigid river"         , ROOM_SANDY_BEACH         , FOBJ_RIVER           },
  { "frigid river"         , ROOM_ARAGAIN_FALLS       , FOBJ_RIVER           },
  { "frigid river"         , ROOM_END_OF_RAINBOW      , FOBJ_RIVER           },
  { "frigid river"         , ROOM_CANYON_BOTTOM       , FOBJ_RIVER           },
  { "frigid river"         , ROOM_CLIFF_MIDDLE        , FOBJ_RIVER           },
  { "frigid river"         , ROOM_CANYON_VIEW         , FOBJ_RIVER           },
  { "river"                , ROOM_DAM_BASE            , FOBJ_RIVER           },
  { "river"                , ROOM_RIVER_1             , FOBJ_RIVER           },
  { "river"                , ROOM_RIVER_2             , FOBJ_RIVER           },
  { "river"                , ROOM_RIVER_3             , FOBJ_RIVER           },
  { "river"                , ROOM_WHITE_CLIFFS_NORTH  , FOBJ_RIVER           },
  { "river"                , ROOM_WHITE_CLIFFS_SOUTH  , FOBJ_RIVER           },
  { "river"                , ROOM_RIVER_4             , FOBJ_RIVER           },
  { "river"                , ROOM_RIVER_5             , FOBJ_RIVER           },
  { "river"                , ROOM_SHORE               , FOBJ_RIVER           },
  { "river"                , ROOM_SANDY_BEACH         , FOBJ_RIVER           },
  { "river"                , ROOM_ARAGAIN_FALLS       , FOBJ_RIVER           },
  { "river"                , ROOM_END_OF_RAINBOW      , FOBJ_RIVER           },
  { "river"                , ROOM_CANYON_BOTTOM       , FOBJ_RIVER           },
  { "river"                , ROOM_CLIFF_MIDDLE        , FOBJ_RIVER           },
  { "river"                , ROOM_CANYON_VIEW         , FOBJ_RIVER           },
  { "rickety ladder"       , ROOM_LADDER_TOP          , FOBJ_LADDER          },
  { "rickety ladder"       , ROOM_LADDER_BOTTOM       , FOBJ_LADDER          },
  { "narrow ladder"        , ROOM_LADDER_TOP          , FOBJ_LADDER          },
  { "narrow ladder"        , ROOM_LADDER_BOTTOM       , FOBJ_LADDER          },
  { "wooden ladder"        , ROOM_LADDER_TOP          , FOBJ_LADDER          },
  { "wooden ladder"        , ROOM_LADDER_BOTTOM       , FOBJ_LADDER          },
  { "ladder"               , ROOM_LADDER_TOP          , FOBJ_LADDER          },
  { "ladder"               , ROOM_LADDER_BOTTOM       , FOBJ_LADDER          },
  { "trap door"            , ROOM_LIVING_ROOM         , FOBJ_TRAP_DOOR       },
  { "trap door"            , ROOM_CELLAR              , FOBJ_TRAP_DOOR       },
  { "trap"                 , ROOM_LIVING_ROOM         , FOBJ_TRAP_DOOR       },
  { "trap"                 , ROOM_CELLAR              , FOBJ_TRAP_DOOR       },
  { "trap-door"            , ROOM_LIVING_ROOM         , FOBJ_TRAP_DOOR       },
  { "trap-door"            , ROOM_CELLAR              , FOBJ_TRAP_DOOR       },
  { "trapdoor"             , ROOM_LIVING_ROOM         , FOBJ_TRAP_DOOR       },
  { "trapdoor"             , ROOM_CELLAR              , FOBJ_TRAP_DOOR       },
  { "door"                 , ROOM_LIVING_ROOM         , FOBJ_AMB             },  // two doors in this room
  { "door"                 , ROOM_CELLAR              , FOBJ_TRAP_DOOR       },
  { "stairs"               , ROOM_KITCHEN             , FOBJ_STAIRS          },
  { "stairs"               , ROOM_ATTIC               , FOBJ_STAIRS          },
  { "stairs"               , ROOM_LIVING_ROOM         , FOBJ_STAIRS          },
  { "stairs"               , ROOM_CELLAR              , FOBJ_STAIRS          },
  { "stairs"               , ROOM_CYCLOPS_ROOM        , FOBJ_STAIRS          },
  { "stairs"               , ROOM_TREASURE_ROOM       , FOBJ_STAIRS          },
  { "stairs"               , ROOM_RESERVOIR_NORTH     , FOBJ_STAIRS          },
  { "stairs"               , ROOM_SMALL_CAVE          , FOBJ_STAIRS          },
  { "stairs"               , ROOM_TINY_CAVE           , FOBJ_STAIRS          },
  { "stairs"               , ROOM_ATLANTIS_ROOM       , FOBJ_STAIRS          },
  { "stairs"               , ROOM_EW_PASSAGE          , FOBJ_STAIRS          },
  { "stairs"               , ROOM_DEEP_CANYON         , FOBJ_STAIRS          },
  { "stairs"               , ROOM_LOUD_ROOM           , FOBJ_STAIRS          },
  { "stairs"               , ROOM_CHASM_ROOM          , FOBJ_STAIRS          },
  { "stairs"               , ROOM_EGYPT_ROOM          , FOBJ_STAIRS          },
  { "stairs"               , ROOM_TORCH_ROOM          , FOBJ_STAIRS          },
  { "stairs"               , ROOM_NORTH_TEMPLE        , FOBJ_STAIRS          },
  { "stairs"               , ROOM_SMELLY_ROOM         , FOBJ_STAIRS          },
  { "stairs"               , ROOM_GAS_ROOM            , FOBJ_STAIRS          },
  { "stairs"               , ROOM_LADDER_TOP          , FOBJ_STAIRS          },
  { "staircase"            , ROOM_KITCHEN             , FOBJ_STAIRS          },
  { "staircase"            , ROOM_ATTIC               , FOBJ_STAIRS          },
  { "staircase"            , ROOM_LIVING_ROOM         , FOBJ_STAIRS          },
  { "staircase"            , ROOM_CELLAR              , FOBJ_STAIRS          },
  { "staircase"            , ROOM_CYCLOPS_ROOM        , FOBJ_STAIRS          },
  { "staircase"            , ROOM_TREASURE_ROOM       , FOBJ_STAIRS          },
  { "staircase"            , ROOM_RESERVOIR_NORTH     , FOBJ_STAIRS          },
  { "staircase"            , ROOM_SMALL_CAVE          , FOBJ_STAIRS          },
  { "staircase"            , ROOM_TINY_CAVE           , FOBJ_STAIRS          },
  { "staircase"            , ROOM_ATLANTIS_ROOM       , FOBJ_STAIRS          },
  { "staircase"            , ROOM_EW_PASSAGE          , FOBJ_STAIRS          },
  { "staircase"            , ROOM_DEEP_CANYON         , FOBJ_STAIRS          },
  { "staircase"            , ROOM_LOUD_ROOM           , FOBJ_STAIRS          },
  { "staircase"            , ROOM_CHASM_ROOM          , FOBJ_STAIRS          },
  { "staircase"            , ROOM_EGYPT_ROOM          , FOBJ_STAIRS          },
  { "staircase"            , ROOM_TORCH_ROOM          , FOBJ_STAIRS          },
  { "staircase"            , ROOM_NORTH_TEMPLE        , FOBJ_STAIRS          },
  { "staircase"            , ROOM_SMELLY_ROOM         , FOBJ_STAIRS          },
  { "staircase"            , ROOM_GAS_ROOM            , FOBJ_STAIRS          },
  { "staircase"            , ROOM_LADDER_TOP          , FOBJ_STAIRS          },
  { "stairway"             , ROOM_KITCHEN             , FOBJ_STAIRS          },
  { "stairway"             , ROOM_ATTIC               , FOBJ_STAIRS          },
  { "stairway"             , ROOM_LIVING_ROOM         , FOBJ_STAIRS          },
  { "stairway"             , ROOM_CELLAR              , FOBJ_STAIRS          },
  { "stairway"             , ROOM_CYCLOPS_ROOM        , FOBJ_STAIRS          },
  { "stairway"             , ROOM_TREASURE_ROOM       , FOBJ_STAIRS          },
  { "stairway"             , ROOM_RESERVOIR_NORTH     , FOBJ_STAIRS          },
  { "stairway"             , ROOM_SMALL_CAVE          , FOBJ_STAIRS          },
  { "stairway"             , ROOM_TINY_CAVE           , FOBJ_STAIRS          },
  { "stairway"             , ROOM_ATLANTIS_ROOM       , FOBJ_STAIRS          },
  { "stairway"             , ROOM_EW_PASSAGE          , FOBJ_STAIRS          },
  { "stairway"             , ROOM_DEEP_CANYON         , FOBJ_STAIRS          },
  { "stairway"             , ROOM_LOUD_ROOM           , FOBJ_STAIRS          },
  { "stairway"             , ROOM_CHASM_ROOM          , FOBJ_STAIRS          },
  { "stairway"             , ROOM_EGYPT_ROOM          , FOBJ_STAIRS          },
  { "stairway"             , ROOM_TORCH_ROOM          , FOBJ_STAIRS          },
  { "stairway"             , ROOM_NORTH_TEMPLE        , FOBJ_STAIRS          },
  { "stairway"             , ROOM_SMELLY_ROOM         , FOBJ_STAIRS          },
  { "stairway"             , ROOM_GAS_ROOM            , FOBJ_STAIRS          },
  { "stairway"             , ROOM_LADDER_TOP          , FOBJ_STAIRS          },
  { "mountain range"       , ROOM_MOUNTAINS           , FOBJ_MOUNTAIN_RANGE  },
  { "range"                , ROOM_MOUNTAINS           , FOBJ_MOUNTAIN_RANGE  },
  { "mountain"             , ROOM_MOUNTAINS           , FOBJ_MOUNTAIN_RANGE  },
  { "mountains"            , ROOM_MOUNTAINS           , FOBJ_MOUNTAIN_RANGE  },
  { "large bolt"           , ROOM_DAM_ROOM            , FOBJ_BOLT            },
  { "metal bolt"           , ROOM_DAM_ROOM            , FOBJ_BOLT            },
  { "large nut"            , ROOM_DAM_ROOM            , FOBJ_BOLT            },
  { "metal nut"            , ROOM_DAM_ROOM            , FOBJ_BOLT            },
  { "bolt"                 , ROOM_DAM_ROOM            , FOBJ_BOLT            },
  { "nut"                  , ROOM_DAM_ROOM            , FOBJ_BOLT            },
  { "small bubble"         , ROOM_DAM_ROOM            , FOBJ_BUBBLE          },
  { "green bubble"         , ROOM_DAM_ROOM            , FOBJ_BUBBLE          },
  { "bubble"               , ROOM_DAM_ROOM            , FOBJ_BUBBLE          },
  { "altar"                , ROOM_SOUTH_TEMPLE        , FOBJ_ALTAR           },
  { "kitchen table"        , ROOM_KITCHEN             , FOBJ_KITCHEN_TABLE   },
  { "table"                , ROOM_KITCHEN             , FOBJ_KITCHEN_TABLE   },
  { "table"                , ROOM_ATTIC               , FOBJ_ATTIC_TABLE     },
  { "yellow button"        , ROOM_MAINTENANCE_ROOM    , FOBJ_YELLOW_BUTTON   },
  { "button"               , ROOM_MAINTENANCE_ROOM    , FOBJ_AMB             },  // four buttons in this room
  { "brown button"         , ROOM_MAINTENANCE_ROOM    , FOBJ_BROWN_BUTTON    },
  { "button"               , ROOM_MAINTENANCE_ROOM    , FOBJ_AMB             },  // four buttons in this room
  { "red button"           , ROOM_MAINTENANCE_ROOM    , FOBJ_RED_BUTTON      },
  { "button"               , ROOM_MAINTENANCE_ROOM    , FOBJ_AMB             },  // four buttons in this room
  { "blue button"          , ROOM_MAINTENANCE_ROOM    , FOBJ_BLUE_BUTTON     },
  { "button"               , ROOM_MAINTENANCE_ROOM    , FOBJ_AMB             },  // four buttons in this room
  { "large carpet"         , ROOM_LIVING_ROOM         , FOBJ_RUG             },
  { "oriental carpet"      , ROOM_LIVING_ROOM         , FOBJ_RUG             },
  { "large rug"            , ROOM_LIVING_ROOM         , FOBJ_RUG             },
  { "oriental rug"         , ROOM_LIVING_ROOM         , FOBJ_RUG             },
  { "carpet"               , ROOM_LIVING_ROOM         , FOBJ_RUG             },
  { "rug"                  , ROOM_LIVING_ROOM         , FOBJ_RUG             },
  { "dam"                  , ROOM_DAM_ROOM            , FOBJ_DAM             },
  { "gate"                 , ROOM_DAM_ROOM            , FOBJ_DAM             },
  { "gates"                , ROOM_DAM_ROOM            , FOBJ_DAM             },
  { "front door"           , ROOM_WEST_OF_HOUSE       , FOBJ_FRONT_DOOR      },
  { "boarded door"         , ROOM_WEST_OF_HOUSE       , FOBJ_FRONT_DOOR      },
  { "door"                 , ROOM_WEST_OF_HOUSE       , FOBJ_FRONT_DOOR      },
  { "huge door"            , ROOM_STONE_BARROW        , FOBJ_BARROW_DOOR     },
  { "stone door"           , ROOM_STONE_BARROW        , FOBJ_BARROW_DOOR     },
  { "door"                 , ROOM_STONE_BARROW        , FOBJ_BARROW_DOOR     },
  { "massive barrow"       , ROOM_STONE_BARROW        , FOBJ_BARROW          },
  { "stone barrow"         , ROOM_STONE_BARROW        , FOBJ_BARROW          },
  { "barrow"               , ROOM_STONE_BARROW        , FOBJ_BARROW          },
  { "skeleton"             , ROOM_MAZE_5              , FOBJ_BONES           },
  { "leaky pipe"           , ROOM_MAINTENANCE_ROOM    , FOBJ_LEAK            },
  { "leak"                 , ROOM_MAINTENANCE_ROOM    , FOBJ_LEAK            },
  { "pipe"                 , ROOM_MAINTENANCE_ROOM    , FOBJ_LEAK            },
  { "enormous mirror"      , ROOM_MIRROR_ROOM_2       , FOBJ_MIRROR2         },
  { "mirror"               , ROOM_MIRROR_ROOM_2       , FOBJ_MIRROR2         },
  { "reflection"           , ROOM_MIRROR_ROOM_2       , FOBJ_MIRROR2         },
  { "enormous mirror"      , ROOM_MIRROR_ROOM_1       , FOBJ_MIRROR1         },
  { "mirror"               , ROOM_MIRROR_ROOM_1       , FOBJ_MIRROR1         },
  { "reflection"           , ROOM_MIRROR_ROOM_1       , FOBJ_MIRROR1         },
  { "ancient inscription"  , ROOM_NORTH_TEMPLE        , FOBJ_PRAYER          },
  { "ancient prayer"       , ROOM_NORTH_TEMPLE        , FOBJ_PRAYER          },
  { "inscription"          , ROOM_NORTH_TEMPLE        , FOBJ_PRAYER          },
  { "prayer"               , ROOM_NORTH_TEMPLE        , FOBJ_PRAYER          },
  { "wooden railing"       , ROOM_DOME_ROOM           , FOBJ_RAILING         },
  { "wooden rail"          , ROOM_DOME_ROOM           , FOBJ_RAILING         },
  { "railing"              , ROOM_DOME_ROOM           , FOBJ_RAILING         },
  { "rail"                 , ROOM_DOME_ROOM           , FOBJ_RAILING         },
  { "sand"                 , ROOM_SANDY_CAVE          , FOBJ_SAND            },
  { "switch"               , ROOM_MACHINE_ROOM        , FOBJ_MACHINE_SWITCH  },
  { "wooden door"          , ROOM_LIVING_ROOM         , FOBJ_WOODEN_DOOR     },
  { "gothic lettering"     , ROOM_LIVING_ROOM         , FOBJ_WOODEN_DOOR     },
  { "lettering"            , ROOM_LIVING_ROOM         , FOBJ_WOODEN_DOOR     },
  { "door"                 , ROOM_LIVING_ROOM         , FOBJ_AMB             },  // two doors in this room
  { "white pedestal"       , ROOM_TORCH_ROOM          , FOBJ_PEDESTAL        },
  { "marble pedestal"      , ROOM_TORCH_ROOM          , FOBJ_PEDESTAL        },
  { "pedestal"             , ROOM_TORCH_ROOM          , FOBJ_PEDESTAL        },
  { "control panel"        , ROOM_DAM_ROOM            , FOBJ_CONTROL_PANEL   },
  { "panel"                , ROOM_DAM_ROOM            , FOBJ_CONTROL_PANEL   },
  { "nails"                , ROOM_LIVING_ROOM         , FOBJ_NAILS           },
  { "nail"                 , ROOM_LIVING_ROOM         , FOBJ_NAILS           },
  { "granite wall"         , ROOM_TREASURE_ROOM       , FOBJ_GRANITE_WALL    },
  { "granite wall"         , ROOM_NORTH_TEMPLE        , FOBJ_GRANITE_WALL    },
  { "iron chain"           , ROOM_SHAFT_ROOM          , FOBJ_CHAIN           },
  { "chain"                , ROOM_SHAFT_ROOM          , FOBJ_CHAIN           },
  { "iron chain"           , ROOM_LOWER_SHAFT         , FOBJ_CHAIN           },
  { "chain"                , ROOM_LOWER_SHAFT         , FOBJ_CHAIN           },
  { "gate"                 , ROOM_ENTRANCE_TO_HADES   , FOBJ_GATE            },
  { "gateway"              , ROOM_ENTRANCE_TO_HADES   , FOBJ_GATE            },
  { "door"                 , ROOM_STUDIO              , FOBJ_STUDIO_DOOR     },
  { "paint"                , ROOM_STUDIO              , FOBJ_STUDIO_DOOR     },

  {0, 0, 0}
};



struct TREASURESCORE_STRUCT TreasureScore[NUM_TREASURESCORES] =
{
//                   take case
//  obj              valu valu flags

  { OBJ_EGG          ,  5 ,  5 , 0 },
  { OBJ_CANARY       ,  6 ,  4 , 0 },
  { OBJ_PAINTING     ,  4 ,  6 , 0 },
  { OBJ_BAR          , 10 ,  5 , 0 },
  { OBJ_TORCH        , 14 ,  6 , 0 },
  { OBJ_COFFIN       , 10 , 15 , 0 },
  { OBJ_SCEPTRE      ,  4 ,  6 , 0 },
  { OBJ_TRUNK        , 15 ,  5 , 0 },
  { OBJ_TRIDENT      ,  4 , 11 , 0 },
  { OBJ_JADE         ,  5 ,  5 , 0 },
  { OBJ_BRACELET     ,  5 ,  5 , 0 },
  { OBJ_DIAMOND      , 10 , 10 , 0 },
  { OBJ_BAG_OF_COINS , 10 ,  5 , 0 },
  { OBJ_SKULL        , 10 , 10 , 0 },
  { OBJ_SCARAB       ,  5 ,  5 , 0 },
  { OBJ_EMERALD      ,  5 , 10 , 0 },
  { OBJ_CHALICE      , 10 ,  5 , 0 },
  { OBJ_POT_OF_GOLD  , 10 , 10 , 0 },
  { OBJ_BAUBLE       ,  1 ,  1 , 0 }
};



struct ROOMSCORE_STRUCT RoomScore[NUM_ROOMSCORES] =
{
//  obj                 valu flag

  { ROOM_KITCHEN       , 10 , 0 },
  { ROOM_CELLAR        , 25 , 0 },
  { ROOM_EW_PASSAGE    ,  5 , 0 },
  { ROOM_LOWER_SHAFT   , 13 , 0 },
  { ROOM_TREASURE_ROOM , 25 , 0 }
};
